In [ ]:
!wget -c https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh
!chmod +x Miniconda3-py37_4.8.3-Linux-x86_64.sh
!time bash ./Miniconda3-py37_4.8.3-Linux-x86_64.sh -b -f -p /usr/local
!time conda install -q -y -c conda-forge rdkit

import sys
sys.path.append('/usr/local/lib/python3.7/site-packages/')

--2020-11-26 07:06:03--  https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.18.201.79, 104.18.200.79, 2606:4700::6812:c84f, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.18.201.79|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh [following]
--2020-11-26 07:06:03--  https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.131.3, 104.16.130.3, 2606:4700::6810:8203, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.131.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 88867207 (85M) [application/x-sh]
Saving to: ‘Miniconda3-py37_4.8.3-Linux-x86_64.sh’

Miniconda3-py37_4.8 100%[===================>]  84.75M   249MB/s    in 0.3s    

2020-11-26 07:06:03 (249 MB/s) - ‘Minicon

In [ ]:
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
with open('/content/gdrive/My Drive/test.txt', 'w') as w:
  w.write('colab test')
with open('/content/gdrive/My Drive/test.txt') as f:
  lines = f.readlines()
print(lines)

['colab test']


In [ ]:
import numpy as np
a=[1,2,3]
numpy_a = np.array(a)

In [ ]:
print(a)
print(numpy_a)
print(type(a), type(numpy_a))

[1, 2, 3]
[1 2 3]
<class 'list'> <class 'numpy.ndarray'>


In [ ]:
b=[4,5,6]
#list는 이렇게해야함
n=len(a)
c=[]
for i in range(len(a)):
  c.append(a[i]+b[i])
print(c)
#numpy는 한방에가능
print(numpy_a+np.array(b))

[5, 7, 9]
[5 7 9]


In [ ]:
import torch

In [ ]:
a = [1,2,3]
torch_a = torch.Tensor(a)
print(torch_a)
a=np.array(a)
torch_a = torch.Tensor(a)
print(torch_a)
#list나 numpy나 다 텐서가된다. flexible해서 쓰기편하다. 텐서:mxn은 행렬이고 그 위. mxnxl
#numpy는 그래디언트가 안되는데 토치는 된다.
x= torch.Tensor([1])
x.requires_grad_()
y=x**2
print(x) 
print(y)
y.backward()
print(x.grad)

tensor([1., 2., 3.])
tensor([1., 2., 3.])
tensor([1.], requires_grad=True)
tensor([1.], grad_fn=<PowBackward0>)
tensor([2.])


In [ ]:
a= np.ones((3000,3000))
torch_a = torch.Tensor(a)
cuda_a = torch_a.cuda()
print(a)
print(torch_a)
print(cuda_a)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])
tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]], device='cuda:0')


In [ ]:
import time
start = time.time()
b = np.matmul(a,a)
end = time.time()
print('time for cpu, numpy',end-start)
start = time.time()
b = torch.matmul(torch_a,torch_a)
end = time.time()
print('time for cpu, torch',end-start)
start = time.time()
b = torch.matmul(cuda_a,cuda_a)
end = time.time()
print('time for gpu, torch',end-start)



time for cpu, numpy 1.6471471786499023
time for cpu, torch 0.8632850646972656
time for gpu, torch 0.006298542022705078


In [ ]:
import torch.nn as nn

In [ ]:
 a= torch.Tensor([-2,-1,0,1,2])
 activation = nn.ReLU() 
 #activation = nn.Sigmoid()
 print(activation(a))
 #nn.ReLU(a)는 안됨. 이거는 layer고 어떤 객체가 아니다. 그래서 하면안된다. 레이어를 만들고 펑션을 씌워라
 #nn.ReLU는 펑션이 아니라서 이렇게 못한다.
#ReLu나 다른거는 Regression. sigmoid는 바이너리 분류.

tensor([0., 0., 0., 1., 2.])


In [ ]:
activation = nn.Softmax(dim=-1) #dimension이 -1인 layer를 만든다.
print(activation(a))
#다 합치면 1이다. 확률을 올려주는것. 따라서 multi classification은 대부분 소프트맥스쓴다.
#binary는 sigmoid=softmax이다. 

tensor([0.0117, 0.0317, 0.0861, 0.2341, 0.6364])


In [ ]:
relu = nn.ReLU()
sigmoid = nn.Sigmoid()
a = torch.Tensor([-2,-1,0,1,2])
a = relu(a)
a = sigmoid(a)
print (a)

tensor([0.5000, 0.5000, 0.5000, 0.7311, 0.8808])


In [ ]:
n = 3
layers = []
for i in range(n):
  layers.append(nn.Sigmoid())
layers.append(nn.ReLU())
x = torch.Tensor([0,1,2,3,4])
for layer in layers:
  x = layer(x)
print(x)
x=layers[0](x)
print(x)

tensor([0.6508, 0.6626, 0.6697, 0.6730, 0.6743])
tensor([0.6572, 0.6599, 0.6614, 0.6622, 0.6625])


In [ ]:
import torch.nn.functional as F
x=torch.Tensor([-2,-1,0,1,2])
y=F.sigmoid(x)
print(y)
y=F.relu(x)
print(y)

tensor([0.1192, 0.2689, 0.5000, 0.7311, 0.8808])
tensor([0., 0., 0., 1., 2.])


/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1625: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


In [ ]:
#Problem 1
n=3
layers = []
for i in range(n):
  layers.append(nn.ReLU())
  layers.append(nn.Sigmoid())
print(layers)
x = torch.Tensor([-2,-1,0,1,2])
for layer in layers:
  if layer == nn.Sigmoid():
    x = layer(x)-1/3
  else: 
    x = layer(x)
print(x)







[ReLU(), Sigmoid(), ReLU(), Sigmoid(), ReLU(), Sigmoid()]
tensor([0.6508, 0.6508, 0.6508, 0.6626, 0.6697])


In [ ]:
#Problem 2
a = np.random.uniform(0,1,100000000)
torch_a = torch.Tensor(a)
cuda_a = torch_a.cuda()

start = time.time()
for layer in layers:
  if layer == nn.Sigmoid():
    torch_a = layer(torch_a) - 1/3
  else:
    torch_a = layer(torch_a)
end = time.time()
print('time for cpu',end-start)

start = time.time()
for layer in layers:
  if layer == nn.Sigmoid():
    cuda_a = layer(cuda_a) - 1/3
  else:
    cuda_a = layer(cuda_a)
end = time.time()
print('time for gpu',end-start)


time for cpu 1.104882001876831
time for gpu 0.0127410888671875


In [ ]:
#CLASS torch.nn.Linear(in_features: int,out_features: int, bias:bool=True)
#y=Wx+b 꼴임. bias에서 False하면 b 안들어감. 
#nn.Linear(512,256)이면 input이 512차원, output이 256차원.


#1. data만들기 2. 모델만들기 3. data load하기, loader정의하기
#4. training parameter만들기 5. train하기 6. validation하기

In [ ]:
#1. data만들기 
#1) preprocessing하기. 분자는 못읽으니까 분자를 수치화 비슷하게 해야 인식가능.
#2) init function. supervise니까 input과 label을 만들자.
#3) len은 dataset길이인데 넣든말든. getitem은 반드시 넣어야 data에서 원하는것만 뽑아쓰기가능



In [ ]:
from rdkit import Chem
from rdkit.Chem.Crippen import MolLogP
from rdkit import Chem, DataStructs
from rdkit.Chem import AllChem
import numpy as np
import torch
import time
from rdkit.Chem import rdMolDescriptors
from torch.utils.data import Dataset, DataLoader # 이거하면 torch에있는 좋은데이터 사용가능

import torch.nn as nn
import torch.nn.functional as F

#### Preparation of data!!! ####
class DataSet(Dataset):
    
    def __init__(self,smiles):
        morgan_fingerprint = []
        log_p = []
        num_data = len(smiles)
        self.smiles = smiles
        for i in range(num_data):# smiles를 이용해서 분자를 만든다.
            s = smiles[i]
            m = Chem.MolFromSmiles(s)
            # 분자로 fingerprint 받아서(1024차원)
            fp = rdMolDescriptors.GetMorganFingerprintAsBitVect(m,2,nBits=1024)
            logp = MolLogP(m)
            # 두 list에 input x와 label y를 각각 넣는다.
            morgan_fingerprint.append(fp)
            log_p.append(logp)
        #토치화를 시켜서 빠르게할수있게함 이렇게 x랑 y를 만든다.
        #list를 numpy로 바꾸고 그걸 토치텐서로 바꾼거
        self.morgan_fingerprint = torch.from_numpy(np.array(morgan_fingerprint))
        self.log_p = torch.from_numpy(np.array(log_p))

    def __len__(self):#len(a)=3이걸 하려면 이걸 정의해줘야 할수있다.
        return len(self.smiles)

    def __getitem__(self,idx):#getitem쓰고 idx넣었을때 idx에있는 값을 return해라 이렇게 짜면 
    #class data에 몇번째 원소를 뽑아라는게 무난하게 된다. = iterable object로 만드는게 된다.
    #이거 없으면 1000번째있는 logp를 뽑고싶을때 dataset.log_p[1000]이렇게 써야하는데 
    #get item 쓰면 dataset[1000] 이렇게해도 먹힌다.
        sample = dict()
        sample['mfp'] = self.morgan_fingerprint[idx]
        sample['logp'] = self.log_p[idx]
        return sample

#data는 다받았고 이제 모델을 만들자.
class LinearRegressor(nn.Module):
    
    def __init__(self, d_in,d_h,d_out): #init 해야 파라미터가 바뀜
    #15쪽에 박스를 만든다.
        super().__init__()
        self.linear1 = nn.Linear(d_in,d_h)
        self.linear2 = nn.Linear(d_h,d_h)
        self.linear3 = nn.Linear(d_h,d_out)
        self.activation = nn.ReLU() 

    def forward(self, x): #이걸 써서 x를 입력하면 y가 나올수있게한다.
    #15쪽에 박스사이를 연결하는 화살표를 만든다. 진행되도록.
        #relu = self.activation
        retval = self.linear1(x)
        #retval = relu(retval)
        retval = self.linear2(retval)
        #retval = self.activation(retval)
        retval = self.linear3(retval)
        return retval


#data를 로드해주는건데 
####### Loading data ########
def load_data(directory,num):
    f = open(directory,'r')
    smiles_list = []
    for i in range(num):
        line = f.readline()
        words = line.strip().split('\t')
        smiles_list.append(words[-1])
    return smiles_list


# Train: First generate data
smiles_list = load_data('/content/gdrive/My Drive/smiles.txt',10000)
train_data = DataSet(smiles_list[:5000]) # First 5000 molecules = train data
test_data = DataSet(smiles_list[5001:10000]) # Second 5000 molecules = test data

# Prepare data loader
#DataLoader(로드할 데이터, 배치 크기. 트레인은 랜덤성 부여해야해서 셔플해주고 테스트는 어차피 한번씩만 쓰면되니까 셔플안해도됨.
#배치사이즈는 5000개 한번에 넣으면 안되냐? 인데 모델 인풋이 B x 1024인데 배치사이즈가 5000이면 5000 x 1024라서 너무크다.
#그래서 어쩔수없이 배치사이즈를 줄여야한다.
train_data_loader = DataLoader(train_data,batch_size = 128, shuffle = True)
test_data_loader = DataLoader(test_data,batch_size = 128, shuffle = False) # Load data with size 128 (B=128)

# Prepare model
model =  LinearRegressor(1024,256,1) # Construct model


#이제 트레인해야하는데 이건 거의 고정이긴해. 
# Prepare learning parmaters
num_epoch = 10 # Number of scanning whole data 몇번반복해서 쓸거냐
loss_fn = nn.MSELoss() # Mean Square Error Loss: Regression 로스 설정
lr = 1e-4 # Learning rate = 1 x 10^(-4) 뉴럴네트워크 파라미터를 얼마나 크게 바꿀거냐.
optimizer = torch.optim.Adam(model.parameters(),lr=lr) # Adam optimizer 
#옵티마이저는 알고리즘 문젠데 아담 많이쓰더라.  SGD아니면.
#우리는 ㅍ모델의 파라미터를 학습하는거니까 여기에 model.parameters()를 적은거.
# Train process
model.cuda()

for i in range(num_epoch):
    loss_list = []
    for i_batch,batch in enumerate(train_data_loader):
        x_batch = batch['mfp'].float()
        y_batch = batch['logp'].float()#학습할게 스칼라라서 float를 붙였다.
        x_batch = x_batch.cuda()#gpu에 올린다.
        y_batch = y_batch.cuda()
        y_pred = model(x_batch)#예측값을 ypred로 한다.
        y_pred = y_pred.squeeze(1)
        loss = loss_fn(y_pred,y_batch)#로스를계산한다.
        optimizer.zero_grad()
        loss_list.append(loss.data.cpu().numpy())#gpu에있는걸cpu로 내려서 다운받는다.+넘파이가 사용하기 쉬워서 넘파이로.
        loss.backward()#로스를 위에서 어펜드로 저장해놓고 백워드로 로스의 gradient를 계산한다.
        optimizer.step()#optimizer로 loss를 줄이도록 stp()이게 모델에 가하는거라서 모델을 optimize한다.
    avg_loss = np.mean(np.array(loss_list))
    print ('avg loss',avg_loss) #10번(num_epoch) 돌리면서 로스평균을 출력

#model.eval()


######## Validation ########
test_loss_list = []
with torch.no_grad():#이거써야 model에 업데이트가 안된다. 똑같은데 backwardoptimize과정이 없는것.
    for i_batch, batch in enumerate(test_data_loader):
        x_batch = batch['mfp'].float()
        y_batch = batch['logp'].float()
        x_batch = x_batch.cuda()
        y_batch = y_batch.cuda()
        y_pred = model(x_batch)
        y_pred = y_pred.squeeze(1)#dimension문제땜에넣은거.
        loss = loss_fn(y_pred,y_batch)
        loss_list.append(loss.data.cpu().numpy()) 

total_loss = np.mean(np.
                     array(loss_list))
print ('validation loss: ',total_loss)






FileNotFoundError: ignored

In [ ]:
#1.Add ReLU layer between each linear layers for non linear activation
#2. Add another linear activation with non linear activation with relu and compare the result with the original
#3. Change learning rate=1e-5 and epoch=100 and compare the result with the original

from rdkit import Chem
from rdkit.Chem.Crippen import MolLogP
from rdkit import Chem, DataStructs
from rdkit.Chem import AllChem
import numpy as np
import torch
import time
from rdkit.Chem import rdMolDescriptors
from torch.utils.data import Dataset, DataLoader

import torch.nn as nn
import torch.nn.functional as F

#### Preparation of data!!! ####
class DataSet(Dataset):
    
    def __init__(self,smiles):
        morgan_fingerprint = []
        log_p = []
        num_data = len(smiles)
        self.smiles = smiles
        for i in range(num_data):
            s = smiles[i]
            m = Chem.MolFromSmiles(s)
            fp = rdMolDescriptors.GetMorganFingerprintAsBitVect(m,2,nBits=1024)
            logp = MolLogP(m)
            morgan_fingerprint.append(fp)
            log_p.append(logp)
        self.morgan_fingerprint = torch.from_numpy(np.array(morgan_fingerprint))
        self.log_p = torch.from_numpy(np.array(log_p))

    def __len__(self):
        return len(self.smiles)

    def __getitem__(self,idx):
        sample = dict()
        sample['mfp'] = self.morgan_fingerprint[idx]
        sample['logp'] = self.log_p[idx]
        return sample


class LinearRegressor(nn.Module):
    
    def __init__(self, d_in,d_h,d_out):
        super().__init__()
        self.linear1 = nn.Linear(d_in,d_h)
        self.linear2 = nn.Linear(d_h,d_h)
        self.linear3 = nn.Linear(d_h,d_h)
        self.linear4 = nn.Linear(d_h,d_out)
        self.activation = nn.ReLU()

    def forward(self, x):
        relu = self.activation
        retval = self.linear1(x)
        retval = relu(retval)
        retval = self.linear2(retval)
        retval = relu(retval)
        retval = self.linear3(retval)
        retval = relu(retval)
        retval = self.linear4(retval)
        return retval

####### Loading data ########
def load_data(directory,num):
    f = open(directory,'r')
    smiles_list = []
    for i in range(num):
        line = f.readline()
        words = line.strip().split('\t')
        smiles_list.append(words[-1])
    return smiles_list


# Train: First generate data
smiles_list = load_data('/content/gdrive/My Drive/smiles.txt',10000)
train_data = DataSet(smiles_list[:5000]) # First 5000 molecules = train data
test_data = DataSet(smiles_list[5001:10000]) # Second 5000 molecules = test data

# Prepare data loader
train_data_loader = DataLoader(train_data,batch_size = 128, shuffle = True)
test_data_loader = DataLoader(test_data,batch_size = 128, shuffle = False) # Load data with size 128 (B=128)

# Prepare model
model =  LinearRegressor(1024,1024,1) # Construct model

# Prepare learning parmaters
num_epoch = 10 # Number of scanning whole data
loss_fn = nn.MSELoss() # Mean Square Error Loss: Regression
lr = 1e-4 # Learning rate = 1 x 10^(-4)
optimizer = torch.optim.Adam(model.parameters(),lr=lr) # Adam optimizer 

# Train process
model.cuda()

for i in range(num_epoch):
    loss_list = []
    for i_batch,batch in enumerate(train_data_loader):
        x_batch = batch['mfp'].float()
        y_batch = batch['logp'].float()
        x_batch = x_batch.cuda()
        y_batch = y_batch.cuda()
        y_pred = model(x_batch)
        y_pred = y_pred.squeeze(1)
        loss = loss_fn(y_pred,y_batch)
        optimizer.zero_grad()
        loss_list.append(loss.data.cpu().numpy())
        loss.backward()
        optimizer.step()
    avg_loss = np.mean(np.array(loss_list))
    print ('avg loss',avg_loss)

#model.eval()


######## Validation ########
test_loss_list = []
with torch.no_grad():
    for i_batch, batch in enumerate(test_data_loader):
        x_batch = batch['mfp'].float()
        y_batch = batch['logp'].float()
        x_batch = x_batch.cuda()
        y_batch = y_batch.cuda()
        y_pred = model(x_batch)
        y_pred = y_pred.squeeze(1)
        loss = loss_fn(y_pred,y_batch)
        loss_list.append(loss.data.cpu().numpy()) 

total_loss = np.mean(np.array(loss_list))
print ('validation loss: ',total_loss)






avg loss 6.1748643
avg loss 2.3657002
avg loss 1.5925547
avg loss 1.1186459
avg loss 0.8464762
avg loss 0.68039906
avg loss 0.56597865
avg loss 0.437321
avg loss 0.33779985
avg loss 0.2563177
validation loss:  0.76872414


In [ ]:

from rdkit import Chem
from rdkit.Chem.Crippen import MolLogP
from rdkit import Chem, DataStructs
from rdkit.Chem import AllChem
import numpy as np
import torch
import time
from rdkit.Chem import rdMolDescriptors
from torch.utils.data import Dataset, DataLoader

import torch.nn as nn
import torch.nn.functional as F

#### Preparation of data!!! ####
class DataSet(Dataset):
    
    def __init__(self,smiles):
        morgan_fingerprint = []
        log_p = []
        num_data = len(smiles)
        self.smiles = smiles
        for i in range(num_data):
            s = smiles[i]
            m = Chem.MolFromSmiles(s)
            fp = rdMolDescriptors.GetMorganFingerprintAsBitVect(m,2,nBits=1024)
            logp = MolLogP(m)
            morgan_fingerprint.append(fp)
            log_p.append(logp)
        self.morgan_fingerprint = torch.from_numpy(np.array(morgan_fingerprint))
        self.log_p = torch.from_numpy(np.array(log_p))

    def __len__(self):
        return len(self.smiles)

    def __getitem__(self,idx):
        sample = dict()
        sample['mfp'] = self.morgan_fingerprint[idx]
        sample['logp'] = self.log_p[idx]
        return sample


class LinearRegressor(nn.Module):
    
    def __init__(self, d_in,d_h,d_out):
        super().__init__()
        self.linear1 = nn.Linear(d_in,d_h)
        self.linear2 = nn.Linear(d_h,d_h)
        self.linear3 = nn.Linear(d_h,d_h)
        self.linear4 = nn.Linear(d_h,d_out)
        self.activation = nn.ReLU()

    def forward(self, x):
        relu = self.activation
        retval = self.linear1(x)
        retval = relu(retval)
        retval = self.linear2(retval)
        retval = relu(retval)
        retval = self.linear3(retval)
        retval = relu(retval)
        retval = self.linear4(retval)
        return retval

####### Loading data ########
def load_data(directory,num):
    f = open(directory,'r')
    smiles_list = []
    for i in range(num):
        line = f.readline()
        words = line.strip().split('\t')
        smiles_list.append(words[-1])
    return smiles_list


# Train: First generate data
smiles_list = load_data('/content/gdrive/My Drive/smiles.txt',10000)
train_data = DataSet(smiles_list[:5000]) # First 5000 molecules = train data
test_data = DataSet(smiles_list[5001:10000]) # Second 5000 molecules = test data

# Prepare data loader
train_data_loader = DataLoader(train_data,batch_size = 128, shuffle = True)
test_data_loader = DataLoader(test_data,batch_size = 128, shuffle = False) # Load data with size 128 (B=128)

# Prepare model
model =  LinearRegressor(1024,1024,1) # Construct model

# Prepare learning parmaters
num_epoch = 100 # Number of scanning whole data
loss_fn = nn.MSELoss() # Mean Square Error Loss: Regression
lr = 1e-5 # Learning rate = 1 x 10^(-4)
optimizer = torch.optim.Adam(model.parameters(),lr=lr) # Adam optimizer 

# Train process
model.cuda()

for i in range(num_epoch):
    loss_list = []
    for i_batch,batch in enumerate(train_data_loader):
        x_batch = batch['mfp'].float()
        y_batch = batch['logp'].float()
        x_batch = x_batch.cuda()
        y_batch = y_batch.cuda()
        y_pred = model(x_batch)
        y_pred = y_pred.squeeze(1)
        loss = loss_fn(y_pred,y_batch)
        optimizer.zero_grad()
        loss_list.append(loss.data.cpu().numpy())
        loss.backward()
        optimizer.step()
    avg_loss = np.mean(np.array(loss_list))
    print ('avg loss',avg_loss)

#model.eval()


######## Validation ########
test_loss_list = []
with torch.no_grad():
    for i_batch, batch in enumerate(test_data_loader):
        x_batch = batch['mfp'].float()
        y_batch = batch['logp'].float()
        x_batch = x_batch.cuda()
        y_batch = y_batch.cuda()
        y_pred = model(x_batch)
        y_pred = y_pred.squeeze(1)
        loss = loss_fn(y_pred,y_batch)
        loss_list.append(loss.data.cpu().numpy()) 

total_loss = np.mean(np.array(loss_list))
print ('validation loss: ',total_loss)



#밸은 잘 못하는데 train은 loss가 작다. 따라서 테스트가 꾸지니까 이거쓰면 위험. 
#Overfitting!


avg loss 11.219603
avg loss 10.025643
avg loss 7.687744
avg loss 4.4642324
avg loss 3.2328522
avg loss 3.0970643
avg loss 2.831059
avg loss 2.7178879
avg loss 2.52733
avg loss 2.424472
avg loss 2.2190468
avg loss 2.0910516
avg loss 1.9464867
avg loss 1.8411725
avg loss 1.6835167
avg loss 1.5416635
avg loss 1.4391999
avg loss 1.3186122
avg loss 1.2371893
avg loss 1.148283
avg loss 1.0762064
avg loss 1.0025876
avg loss 0.9554822
avg loss 0.9007409
avg loss 0.87075746
avg loss 0.8097881
avg loss 0.8385089
avg loss 0.739087
avg loss 0.7164215
avg loss 0.6816872
avg loss 0.6509579
avg loss 0.6731556
avg loss 0.6042033
avg loss 0.5902225
avg loss 0.565118
avg loss 0.54641837
avg loss 0.52031916
avg loss 0.51530266
avg loss 0.487029
avg loss 0.46685132
avg loss 0.47724906
avg loss 0.4435028
avg loss 0.42877245
avg loss 0.42397037
avg loss 0.39219528
avg loss 0.3719769
avg loss 0.37161392
avg loss 0.34811434
avg loss 0.3344755
avg loss 0.3219755
avg loss 0.3058365
avg loss 0.29509735
avg loss 

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from rdkit import Chem
from rdkit.Chem.Crippen import MolLogP

from torch.utils.data import Dataset, DataLoader

import numpy as np
import time
########## Prepare data ##########

class ConvDataset(Dataset):
    
    def __init__(self,maxlen,c_to_i,smiles_list,property_list):
        self.smiles_list = smiles_list
        self.maxlen = maxlen
        self.c_to_i = c_to_i
        sequence_list = self.encode_smiles()
        sequence_list = np.array(sequence_list)
        self.sequence_list = torch.from_numpy(sequence_list) # x
        self.property_list = torch.from_numpy(np.array(property_list)) # y
   
    def encode_smiles(self):#ccccc이런걸 11111이렇게 컴이 읽을수있게 바꿔줌
        smiles_list = self.smiles_list
        c_to_i = self.c_to_i
        maxlen = self.maxlen
        sequence_list = []
        for smiles in smiles_list:
            sequence = []
            for s in smiles:
                sequence.append(c_to_i[s])
            sequence_list.append(sequence)
        return sequence_list

    def __len__(self):
        return len(self.smiles_list)

    def __getitem__(self, idx):
        sample = dict()
        sample['seq'] = self.sequence_list[idx]
        sample['logP'] = self.property_list[idx]
        return sample


class ConvRegressor(torch.nn.Module):
    
    def __init__(self, n_channel=128, n_conv_layer = 10, kernel_size=3, n_char=46,maxlen = 64):
        super(ConvRegressor, self).__init__()
        convolution_layers = []
        for i in range(n_conv_layer):
            convolution_layers.append(nn.Conv1d(n_channel,n_channel,kernel_size,1,padding = kernel_size//2))
        self.conv = nn.ModuleList(convolution_layers)    
        self.fc = nn.Linear(maxlen * n_channel, 1)
        self.embedding = nn.Embedding(n_char, n_channel)
        self.activation = nn.ReLU()

    def forward(self, x):
        retval = x
        retval = self.embedding(retval)
        retval = retval.permute((0,2,1))
        # Pass conv and dropout
        for layer in self.conv:
            retval = layer(retval)
            retval = self.activation(retval)
        ###### Flatten           
        retval = retval.view(retval.size(0), -1)  
        retval = self.fc(retval)    
        return retval

####### Loading data ########
def load_data(directory,maxlen,num):
    f = open(directory,'r')
    smiles_list = []
    cnt = 0
    while cnt < num:
        line = f.readline()
        words = line.strip().split('\t')
        smiles = words[-1]
        if len(smiles) <= maxlen-1:
            cnt += 1
            smiles_list.append(words[-1])
    return smiles_list

# Encoding
#c = character i = index
#즉 레터를 숫자로 받는다. 사전을 만들어준다.
#딕셔너리에 원소가 없으면 추가하는거임(C:0 O:1 N:2 H:3 이런식으로 계속 추가)
def get_c_to_i(smiles_list):
    c_to_i = dict()
    for smiles in smiles_list:
        for letter in smiles:
            if letter not in c_to_i:
                c_to_i[letter] = len(c_to_i)
    return c_to_i

# Padding
#maxlen 이 최대길이고 여기까지 X로 패딩한다.
def adjust_smiles(smiles_list,maxlen):
    for i in range(len(smiles_list)):
        smiles_list[i] = smiles_list[i].ljust(maxlen,'X')

def calculate_logp(smiles_list):
    logp_list = []
    for smiles in smiles_list:
        mol = Chem.MolFromSmiles(smiles)
        logp = MolLogP(mol)
        logp_list.append(logp)
    return logp_list

# Prepare data
maxlen = 64
smiles_list = load_data('/content/gdrive/My Drive/smiles.txt',maxlen,20000)
logp_list = calculate_logp(smiles_list)
adjust_smiles(smiles_list,maxlen)
c_to_i = get_c_to_i(smiles_list)


# Make train/test/dataloader
train_smiles = smiles_list[:19000]
test_smiles = smiles_list[19000:20000]
train_logp = logp_list[:19000]
test_logp = logp_list[19000:20000]
train_dataset = ConvDataset(maxlen,c_to_i,train_smiles, train_logp)
test_dataset = ConvDataset(maxlen,c_to_i,test_smiles, test_logp)

#Dataloader
train_dataloader = DataLoader(train_dataset, batch_size=32, num_workers=1)
test_dataloader = DataLoader(test_dataset, batch_size=32, num_workers=1)

# Set trainig parameter
model = ConvRegressor(128, 3, 3, len(c_to_i),maxlen)
lr = 1e-4
num_epoch = 30
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
#optimizer = torch.optim.SGD(model.parameters(), lr=lr)
loss_fn = nn.MSELoss()


loss_list = []
st = time.time()

# Load model
model = model.cuda()

for epoch in range(num_epoch):
    epoch_loss = []
    for i_batch, batch in enumerate(train_dataloader):
        x = batch['seq'].cuda() 
        y = batch['logP'].cuda()
        x = x.long()
        y = y.float()
        pred = model(x)
        pred = pred.squeeze(-1)
        loss = loss_fn(pred, y)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        loss_list.append(loss.data.cpu().numpy())
        epoch_loss.append(loss.data.cpu().numpy())
    print (epoch, 'loss: ',np.mean(np.array(loss_list)))
end = time.time()
print ('Time:', end-st)

model.eval()
loss_list = []
with torch.no_grad():
    for i_batch, batch in enumerate(test_dataloader):
        x = batch['seq'].cuda() 
        y = batch['logP'].cuda()
        x = x.long()
        y = y.float()
        pred = model(x)
        pred = pred.squeeze(-1)
        loss = loss_fn(pred, y)
        loss_list.append(loss.data.cpu().numpy())
print ('test loss: ',np.mean(np.array(loss_list)))



0 loss:  1.2311404
1 loss:  0.7512851
2 loss:  0.5539387
3 loss:  0.4448807
4 loss:  0.37642103
5 loss:  0.32830933
6 loss:  0.29360557
7 loss:  0.2655977
8 loss:  0.24389057
9 loss:  0.22641586
10 loss:  0.2115784
11 loss:  0.19853842
12 loss:  0.1876131
13 loss:  0.17808446
14 loss:  0.1696732
15 loss:  0.16223207
16 loss:  0.15555012
17 loss:  0.14960827
18 loss:  0.14393122
19 loss:  0.13902003
20 loss:  0.13433518
21 loss:  0.13019463
22 loss:  0.12626083
23 loss:  0.12272134
24 loss:  0.11923348
25 loss:  0.11620199
26 loss:  0.113161385
27 loss:  0.110418186
28 loss:  0.10776462
29 loss:  0.10524548
Time: 107.64472389221191
test loss:  0.05060501


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from rdkit import Chem
from rdkit.Chem.Crippen import MolLogP

from torch.utils.data import Dataset, DataLoader

import numpy as np
import time
########## Prepare data ##########

class ConvDataset(Dataset):
    
    def __init__(self,maxlen,c_to_i,smiles_list,property_list):
        self.smiles_list = smiles_list
        self.maxlen = maxlen
        self.c_to_i = c_to_i
        sequence_list = self.encode_smiles()
        sequence_list = np.array(sequence_list)
        self.sequence_list = torch.from_numpy(sequence_list) # x
        self.property_list = torch.from_numpy(np.array(property_list)) # y
   
    def encode_smiles(self):#ccccc이런걸 11111이렇게 컴이 읽을수있게 바꿔줌
        smiles_list = self.smiles_list
        c_to_i = self.c_to_i
        maxlen = self.maxlen
        sequence_list = []
        for smiles in smiles_list:
            sequence = []
            for s in smiles:
                sequence.append(c_to_i[s])
            sequence_list.append(sequence)
        return sequence_list

    def __len__(self):
        return len(self.smiles_list)

    def __getitem__(self, idx):
        sample = dict()
        sample['seq'] = self.sequence_list[idx]
        sample['logP'] = self.property_list[idx]
        return sample


class ConvRegressor(torch.nn.Module):
    
    def __init__(self, n_channel=128, n_conv_layer = 2, kernel_size=3, n_char=46,maxlen = 64):
        super(ConvRegressor, self).__init__()
        convolution_layers = []
        for i in range(n_conv_layer):
            convolution_layers.append(nn.Conv1d(n_channel,n_channel,kernel_size,2,padding = kernel_size//2))
        self.conv = nn.ModuleList(convolution_layers)    
        self.fc = nn.Linear(int(maxlen/4) * n_channel, 1)
        self.embedding = nn.Embedding(n_char, n_channel)
        self.activation = nn.Tanh()

    def forward(self, x):
        retval = x
        retval = self.embedding(retval)
        retval = retval.permute((0,2,1))
        # Pass conv and dropout
        for layer in self.conv:
            retval = layer(retval)
            retval = self.activation(retval)
        ###### Flatten           
        retval = retval.view(retval.size(0), -1)  
        retval = self.fc(retval)    
        return retval

####### Loading data ########
def load_data(directory,maxlen,num):
    f = open(directory,'r')
    smiles_list = []
    cnt = 0
    while cnt < num:
        line = f.readline()
        words = line.strip().split('\t')
        smiles = words[-1]
        if len(smiles) <= maxlen-1:
            cnt += 1
            smiles_list.append(words[-1])
    return smiles_list

# Encoding
#c = character i = index
#즉 레터를 숫자로 받는다. 사전을 만들어준다.
#딕셔너리에 원소가 없으면 추가하는거임(C:0 O:1 N:2 H:3 이런식으로 계속 추가)
def get_c_to_i(smiles_list):
    c_to_i = dict()
    for smiles in smiles_list:
        for letter in smiles:
            if letter not in c_to_i:
                c_to_i[letter] = len(c_to_i)
    return c_to_i

# Padding
#maxlen 이 최대길이고 여기까지 X로 패딩한다.
def adjust_smiles(smiles_list,maxlen):
    for i in range(len(smiles_list)):
        smiles_list[i] = smiles_list[i].ljust(maxlen,'X')

def calculate_logp(smiles_list):
    logp_list = []
    for smiles in smiles_list:
        mol = Chem.MolFromSmiles(smiles)
        logp = MolLogP(mol)
        logp_list.append(logp)
    return logp_list

# Prepare data
maxlen = 64
smiles_list = load_data('/content/gdrive/My Drive/smiles.txt',maxlen,20000)
logp_list = calculate_logp(smiles_list)
adjust_smiles(smiles_list,maxlen)
c_to_i = get_c_to_i(smiles_list)


# Make train/test/dataloader
train_smiles = smiles_list[:19000]
test_smiles = smiles_list[19000:20000]
train_logp = logp_list[:19000]
test_logp = logp_list[19000:20000]
train_dataset = ConvDataset(maxlen,c_to_i,train_smiles, train_logp)
test_dataset = ConvDataset(maxlen,c_to_i,test_smiles, test_logp)

#Dataloader
train_dataloader = DataLoader(train_dataset, batch_size=32, num_workers=1)
test_dataloader = DataLoader(test_dataset, batch_size=32, num_workers=1)

# Set trainig parameter
model = ConvRegressor(128, 2, 3, len(c_to_i),maxlen)
lr = 1e-4
num_epoch = 30
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
#optimizer = torch.optim.SGD(model.parameters(), lr=lr)
loss_fn = nn.MSELoss()


loss_list = []
st = time.time()

# Load model
model = model.cuda()

for epoch in range(num_epoch):
    epoch_loss = []
    for i_batch, batch in enumerate(train_dataloader):
        x = batch['seq'].cuda() 
        y = batch['logP'].cuda()
        x = x.long()
        y = y.float()
        pred = model(x)
        pred = pred.squeeze(-1)
        loss = loss_fn(pred, y)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        loss_list.append(loss.data.cpu().numpy())
        epoch_loss.append(loss.data.cpu().numpy())
    print (epoch, 'loss: ',np.mean(np.array(loss_list)))
end = time.time()
print ('Time:', end-st)

model.eval()
loss_list = []
with torch.no_grad():
    for i_batch, batch in enumerate(test_dataloader):
        x = batch['seq'].cuda() 
        y = batch['logP'].cuda()
        x = x.long()
        y = y.float()
        pred = model(x)
        pred = pred.squeeze(-1)
        loss = loss_fn(pred, y)
        loss_list.append(loss.data.cpu().numpy())
print ('test loss: ',np.mean(np.array(loss_list)))



0 loss:  1.3188487
1 loss:  0.98354787
2 loss:  0.81932265
3 loss:  0.7091773
4 loss:  0.6281612
5 loss:  0.565367
6 loss:  0.51562005
7 loss:  0.47549582
8 loss:  0.44186547
9 loss:  0.41405836
10 loss:  0.38969752
11 loss:  0.3686594
12 loss:  0.3502462
13 loss:  0.33397958
14 loss:  0.31943542
15 loss:  0.3061437
16 loss:  0.29418123
17 loss:  0.28336316
18 loss:  0.2733351
19 loss:  0.26413053
20 loss:  0.25568706
21 loss:  0.24775149
22 loss:  0.24031948
23 loss:  0.23338322
24 loss:  0.22698121
25 loss:  0.22089072
26 loss:  0.21514337
27 loss:  0.20976815
28 loss:  0.2046935
29 loss:  0.19993496
Time: 93.5867805480957
test loss:  0.06709999


In [ ]:
print(1)

1


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from rdkit import Chem
from rdkit.Chem.Crippen import MolLogP

from torch.utils.data import Dataset, DataLoader

import numpy as np
import time

########## Prepare data ##########

class RNNDataset(Dataset):
    
    def __init__(self,maxlen,c_to_i,smiles_list,property_list):
        self.smiles_list = smiles_list
        self.maxlen = maxlen
        self.c_to_i = c_to_i
        sequence_list = self.encode_smiles()
        self.length_list = []
        for sequence in sequence_list:
            self.length_list.append(len(sequence))
        self.sequence_list = sequence_list
        self.length_list = np.array(self.length_list)
        self.length_list = torch.from_numpy(self.length_list)
        self.property_list = torch.from_numpy(np.array(property_list))

    def encode_smiles(self):
        smiles_list = self.smiles_list
        c_to_i = self.c_to_i
        maxlen = self.maxlen
        sequence_list = []
        for smiles in smiles_list:
            sequence = []
            for s in smiles:
                sequence.append(c_to_i[s])
            sequence = torch.from_numpy(np.array(sequence))
            sequence_list.append(sequence)
        return sequence_list

    def __len__(self):
        return len(self.smiles_list)

    def __getitem__(self, idx):
        sample = dict()
        sample['length'] = self.length_list[idx]
        sample['seq'] = self.sequence_list[idx]
        sample['logP'] = self.property_list[idx]
        return sample


class RNNRegressor(torch.nn.Module):
    
    def __init__(self, n_feature = 128, n_rnn_layer = 1, n_char=46):
        super().__init__()
        self.rnn = nn.GRU(input_size=n_feature,hidden_size=n_feature,num_layers = n_rnn_layer)
        self.fc = nn.Linear(n_feature,1)
        self.embedding = nn.Embedding(n_char,n_feature)

    def forward(self, x, l):
        x = self.embedding(x)
        # Make x: [N,L,char] into [L, N, char]
        x = x.permute((1,0,2))
        output, h_n = self.rnn(x)
        # l has size batch, showing the length of each smiles
        selected = []
        for i in range(len(l)):
            # l[i]-1: length of ith smiles
            # i: ith sample
            selected.append(output[l[i]-1,i,:])
        retval = torch.stack(selected) # Make one torch tensor
        retval = self.fc(retval) # Evaluated logp for all batches in x
        return retval

####### Loading data ########
def load_data(directory,maxlen,num):
    f = open(directory,'r')
    smiles_list = []
    cnt = 0
    while cnt < num:
        line = f.readline()
        words = line.strip().split('\t')
        smiles = words[-1]
        if len(smiles) <= maxlen-1:
            cnt += 1
            smiles_list.append(words[-1])
    return smiles_list

def get_c_to_i(smiles_list):
    c_to_i = dict()
    for smiles in smiles_list:
        for letter in smiles:
            if letter not in c_to_i:
                c_to_i[letter] = len(c_to_i)
    return c_to_i

def adjust_smiles(smiles_list,maxlen):
    for i in range(len(smiles_list)):
        smiles_list[i] = smiles_list[i].ljust(maxlen,'X')

def add_X(smiles_list):
    for i in range(len(smiles_list)):
        smiles_list[i] += 'X'

def calculate_logp(smiles_list):
    logp_list = []
    for smiles in smiles_list:
        mol = Chem.MolFromSmiles(smiles)
        logp = MolLogP(mol)
        logp_list.append(logp)
    return logp_list

def collate_batch(batch):
    sample = dict()
    seq_batch = []
    l_batch = []
    p_batch = []
    for b in batch:
        l = b['length']
        seq_batch.append(b['seq'])
        l_batch.append(l)
        p_batch.append(b['logP'])
    x = torch.nn.utils.rnn.pad_sequence(seq_batch,batch_first=True,padding_value=42)
    sample['length'] = torch.Tensor(l_batch)
    sample['logP'] = torch.Tensor(p_batch)
    sample['seq'] = x
    return sample

# Prepare data
maxlen = 64
smiles_list = load_data('/content/gdrive/My Drive/smiles.txt',maxlen,20000)
logp_list = calculate_logp(smiles_list)

# Add meaningless letter: 'X'
c_to_i = get_c_to_i(smiles_list)
c_to_i['X'] = len(c_to_i)
print (c_to_i)

# Padding
#adjust_smiles(smiles_list,maxlen)
add_X(smiles_list) # Single padding when using collate function

# Make train/test/dataloader
train_smiles = smiles_list[:19000]
test_smiles = smiles_list[19000:20000]
train_logp = logp_list[:19000]
test_logp = logp_list[19000:20000]
train_dataset = RNNDataset(maxlen,c_to_i,train_smiles, train_logp)
test_dataset = RNNDataset(maxlen,c_to_i,test_smiles, test_logp)

#Dataloader
#train_dataloader = DataLoader(train_dataset, batch_size=32, num_workers=1)
#test_dataloader = DataLoader(test_dataset, batch_size=32, num_workers=1)

train_dataloader = DataLoader(train_dataset, batch_size=32, num_workers=1,collate_fn = collate_batch)
test_dataloader = DataLoader(test_dataset, batch_size=32, num_workers=1,collate_fn = collate_batch)

# Load model
model = RNNRegressor(256,1,len(c_to_i))
model = model.cuda()

# Set training parameter
lr = 1e-4
num_epoch = 20
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
loss_fn = nn.MSELoss()

loss_list = []
st = time.time()


for epoch in range(num_epoch):
    epoch_loss = []
    for i_batch, batch in enumerate(train_dataloader):
        x = batch['seq'].cuda() 
        y = batch['logP'].cuda()
        l = batch['length'].cuda()
        x = x.long()
        y = y.float()
        l = l.long()
        #print ('x',x.shape)
        pred = model(x,l)
        pred = pred.squeeze(-1)
        loss = loss_fn(pred, y)
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        loss_list.append(loss.data.cpu().numpy())
        epoch_loss.append(loss.data.cpu().numpy())
    print (epoch, 'loss: ',np.mean(np.array(loss_list)))

end = time.time()
print ('Time:', end-st)

lost_list = []

model.eval()
with torch.no_grad():
    for i_batch, batch in enumerate(test_dataloader):
        x = batch['seq'].cuda()
        y = batch['logP'].cuda()
        l = batch['length'].cuda()
        x = x.long()
        y = y.float()
        l = l.long()
        pred = model(x,l)
        pred = pred.squeeze(-1)
        loss = loss_fn(pred,y)
        loss_list.append(loss.data.cpu().numpy())
print ('validation loss: ',np.mean(np.array(loss_list)))


{'O': 0, '=': 1, '[': 2, 'N': 3, '+': 4, ']': 5, '(': 6, '-': 7, ')': 8, 'c': 9, '1': 10, '/': 11, 'C': 12, '2': 13, '3': 14, 'n': 15, '\\': 16, '.': 17, 'a': 18, 'l': 19, '#': 20, 'B': 21, 'r': 22, '4': 23, '5': 24, 'I': 25, 'o': 26, 'H': 27, '@': 28, 'L': 29, 'i': 30, 'S': 31, 'K': 32, 'F': 33, 'e': 34, '6': 35, '7': 36, 'G': 37, 'P': 38, 's': 39, 'M': 40, 'g': 41, 'X': 42}
0 loss:  1.2897658
1 loss:  0.79879576
2 loss:  0.60715115
3 loss:  0.49960726
4 loss:  0.42882875
5 loss:  0.3779974
6 loss:  0.3392106
7 loss:  0.30833378
8 loss:  0.2855496
9 loss:  0.26500735
10 loss:  0.24745028
11 loss:  0.23305818
12 loss:  0.21987288
13 loss:  0.20853397
14 loss:  0.19818409
15 loss:  0.18897423
16 loss:  0.18047035
17 loss:  0.17292166
18 loss:  0.16593565
19 loss:  0.15953664
Time: 142.84765601158142
validation loss:  0.15920353


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from rdkit import Chem
from rdkit.Chem.Crippen import MolLogP

#Dataset
from torch.utils.data import Dataset, DataLoader
from rdkit.Chem.rdmolops import GetAdjacencyMatrix

import numpy as np
import time

######### Prepare data ##########

class GCNDataset(Dataset):

    def __init__(self, max_num_atoms, smiles_list):
        self.max_num_atoms = max_num_atoms
        self.smiles_list = smiles_list
        self.property_list = []
        self.input_feature_list = []
        self.adj_list = []
        self.process_data()
        self.property_list = torch.from_numpy(np.array(self.property_list))

    def process_data(self):
        max_num_atoms = self.max_num_atoms
        for smiles in smiles_list:
            mol = Chem.MolFromSmiles(smiles)
            num_atoms = mol.GetNumAtoms()
            # Get padded adj
            adj = GetAdjacencyMatrix(mol) + np.eye(num_atoms)
            padded_adj = np.zeros((max_num_atoms,max_num_atoms))
            padded_adj[:num_atoms,:num_atoms] = adj
            # Get padded feature list
            padded_feature = np.zeros((max_num_atoms,19))
            feature = []
            for i in range(num_atoms):
                feature.append(self.get_atom_feature(mol,i))
                #print(self.get_atom_feature(mol,i))
            feature = np.array(feature)
            # Get property list
            padded_feature[:num_atoms,:19] = feature
            logp = MolLogP(mol)
            self.property_list.append(logp)
            self.input_feature_list.append(torch.from_numpy(padded_feature))
            self.adj_list.append(torch.from_numpy(padded_adj))

    def __len__(self):
        return len(self.smiles_list)

    def __getitem__(self, idx):
        sample = dict()
        sample['feature'] = self.input_feature_list[idx]
        sample['adj'] = self.adj_list[idx]
        sample['logp'] = self.property_list[idx]
        return sample


    def one_of_k_encoding(self, x, allowable_set):
        """Maps inputs not in the allowable set to the last element."""
        if x not in allowable_set:
            x = allowable_set[-1]
        return list(map(lambda s: x == s, allowable_set))

    def get_atom_feature(self, m, atom_i):

        atom = m.GetAtomWithIdx(atom_i)
        return np.array(self.one_of_k_encoding(atom.GetSymbol(),['C','N','O','F','S','Cl','P','ELSE']) +
                        self.one_of_k_encoding(atom.GetTotalNumHs(), [0, 1, 2, 3, 4, 'ELSE']) +
                        self.one_of_k_encoding(atom.GetFormalCharge(),[-1,0,1,'ELSE']) +
                        [atom.GetIsAromatic()])    # (5, 6, 4, 1) --> total 16


class GConvRegressor(torch.nn.Module):

    def __init__(self, n_feature=128, n_layer = 10):
        super(GConvRegressor, self).__init__()
        layer_list = []
        for i in range(n_layer):
            layer_list.append(nn.Linear(n_feature,n_feature))
        self.W = nn.ModuleList(layer_list)
        self.embedding = nn.Linear(19, n_feature) # Do not use Embedding!
        self.fc = nn.Linear(n_feature, 1)

    def forward(self, x, A):
        x = self.embedding(x)
        for l in self.W:
            x = l(x)
            #x = torch.einsum('ijk,ikl->ijl', (A.clone(), x))
            x = torch.matmul(A,x)
            x = F.relu(x)
        x = x.mean(1)

        retval = self.fc(x)

        return retval

####### Loading data ########
def load_data(directory,maxlen,num):
    f = open(directory,'r')
    smiles_list = []
    cnt = 0
    while cnt < num:
        line = f.readline()
        words = line.strip().split('\t')
        smiles = words[-1]
        if len(smiles) <= maxlen-1:
            cnt += 1
            smiles_list.append(words[-1])
    return smiles_list


# Prepare data
max_natoms = 64
maxlen = 64
smiles_list = load_data('/content/gdrive/My Drive/smiles.txt',maxlen,20000)

# Make train/test/dataloader
train_smiles = smiles_list[:19000]
test_smiles = smiles_list[19000:20000]
train_dataset = GCNDataset(max_natoms,train_smiles)
test_dataset = GCNDataset(max_natoms,test_smiles)

#Dataloader
train_dataloader = DataLoader(train_dataset, batch_size=128, num_workers=1)
test_dataloader = DataLoader(test_dataset, batch_size=128, num_workers=1)

# Make model
model = GConvRegressor(128, 5).cuda()

# Training parameter
lr = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
num_epoch = 20
#optimizer = torch.optim.SGD(model.parameters(), lr=lr)
loss_fn = nn.MSELoss()


loss_list = []
st = time.time()

model.cuda()

for epoch in range(num_epoch):
    loss_list = []
    for i_batch, batch in enumerate(train_dataloader):
        x = batch['feature'].cuda().float()
        y = batch['logp'].cuda().float()
        adj = batch['adj'].cuda().float()
        pred = model(x, adj).squeeze(-1)
        loss = loss_fn(pred, y)
        optimizer.zero_grad()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        loss.backward()
        optimizer.step()
        loss_list.append(loss.data.cpu().numpy())
    print (epoch + 1, np.mean(np.array(loss_list)))

end = time.time()
print ('Time:', end-st)
model.eval()
with torch.no_grad():
    loss_list = []
    for i_batch, batch in enumerate(test_dataloader):
        x = batch['feature'].cuda().float()
        y = batch['logp'].cuda().float()
        adj = batch['adj'].cuda().float()
        pred = model(x, adj).squeeze(-1)
        loss = loss_fn(pred, y)
        loss_list.append(loss.data.cpu().numpy())
    print ('validity: ',np.mean(np.array(loss_list)))


스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 False False False  True False False  True]
[ True False False False False False False False  True False False False
 False False False  True False False False]
[False False  True False False False False False  True False False False
 False False False  True False False False]
[ True False False False False False False False False  True False False
 False False False  True False False False]
[ True False False False False False False False False  True False False
 False False False  True False False False]
[ True False False False False False False False  True False False False
 False False False  True False False  True]
[ True False False False False False False False False  True False False
 False False False  True False False  True]
[ True False False False False False False False False  True False False
 False False False  True False False  True]
[ True False False False False False False False False  True False False
 False False False  True Fal

KeyboardInterrupt: ignored

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from rdkit import Chem
from rdkit.Chem.Crippen import MolLogP

from torch.utils.data import Dataset, DataLoader

import numpy as np
import time
########## Prepare data ##########

class ConvDataset(Dataset):
    
    def __init__(self,maxlen,c_to_i,smiles_list,property_list):
        self.smiles_list = smiles_list
        self.maxlen = maxlen
        self.c_to_i = c_to_i
        sequence_list = self.encode_smiles()
        self.sequence_list = sequence_list
        #sequence_list = np.array(sequence_list)
        #self.sequence_list = torch.from_numpy(sequence_list) # x
        self.property_list = torch.from_numpy(np.array(property_list)) # y
   
    def encode_smiles(self):
        smiles_list = self.smiles_list
        c_to_i = self.c_to_i
        maxlen = self.maxlen
        sequence_list = []
        for smiles in smiles_list:
            sequence = []
            for s in smiles:
                sequence.append(c_to_i[s])
            sequence = torch.from_numpy(np.array(sequence))
            sequence_list.append(sequence)
        return sequence_list

    def __len__(self):
        return len(self.smiles_list)

    def __getitem__(self, idx):
        sample = dict()
        sample['seq'] = self.sequence_list[idx]
        sample['logP'] = self.property_list[idx]
        return sample


class ConvRegressor(torch.nn.Module):
    
    def __init__(self, n_channel=128, n_conv_layer = 10, kernel_size=3, n_char=46,maxlen = 64):
        super(ConvRegressor, self).__init__()
        convolution_layers = []
        length_sequence = [64]
        stride = 1
        dilation = 1
        padding = kernel_size//2
        for i in range(n_conv_layer):
            l = (length_sequence[-1] + 2 * padding - dilation * (kernel_size - 1) - 1)/stride + 1
            l = int(l)
            length_sequence.append(l)
        for i in range(n_conv_layer):
            convolution_layers.append(nn.Conv1d(n_channel,n_channel,kernel_size,stride,padding = padding))
        self.conv = nn.ModuleList(convolution_layers)
        self.fc = nn.Linear(length_sequence[-1] * n_channel, 1)
        self.embedding = nn.Embedding(n_char, n_channel)
        self.activation = nn.ReLU()

    def forward(self, x):
        retval = x
        retval = self.embedding(retval)
        retval = retval.permute((0,2,1))
        # Pass conv and dropout
        for layer in self.conv:
            #print ('shape',retval.shape)
            retval = layer(retval)
            retval = self.activation(retval)
        ###### Flatten           
        #retval = torch.mean(retval,-1)
        retval = retval.view(retval.size(0), -1)  
        #retval = retval.unsqueeze(-1)
        retval = self.fc(retval)
        return retval

####### Loading data ########
def load_data(directory,maxlen,num):
    f = open(directory,'r')
    smiles_list = []
    cnt = 0
    while cnt < num:
        line = f.readline()
        words = line.strip().split('\t')
        smiles = words[-1]
        if len(smiles) <= maxlen-1:
            cnt += 1
            smiles_list.append(words[-1])
    return smiles_list

# Encoding
def get_c_to_i(smiles_list):
    c_to_i = dict()
    for smiles in smiles_list:
        for letter in smiles:
            if letter not in c_to_i:
                c_to_i[letter] = len(c_to_i)
    return c_to_i

# Padding
def adjust_smiles(smiles_list,maxlen):
    for i in range(len(smiles_list)):
        smiles_list[i] = smiles_list[i].ljust(maxlen,'X')

def calculate_logp(smiles_list):
    logp_list = []
    for smiles in smiles_list:
        mol = Chem.MolFromSmiles(smiles)
        logp = MolLogP(mol)
        logp_list.append(logp)
    return logp_list

# Prepare data
maxlen = 64
num_data = 20000

smiles_list = load_data('smiles.txt',maxlen,num_data)
logp_list = calculate_logp(smiles_list)
adjust_smiles(smiles_list,maxlen)
c_to_i = get_c_to_i(smiles_list)

num_train = 15000

# Make train/test/dataloader
train_smiles = smiles_list[:num_train]
test_smiles = smiles_list[num_train:num_data]
train_logp = logp_list[:num_train]
test_logp = logp_list[num_train:num_data]
train_dataset = ConvDataset(maxlen,c_to_i,train_smiles, train_logp)
test_dataset = ConvDataset(maxlen,c_to_i,test_smiles, test_logp)

#Dataloader
train_dataloader = DataLoader(train_dataset, batch_size=32, num_workers=1)
test_dataloader = DataLoader(test_dataset, batch_size=32, num_workers=1)

# lr decay
n_channel = 64
num_layer = 3
model = ConvRegressor(n_channel, num_layer, 5, len(c_to_i),maxlen)
lr = 1e-4
num_epoch = 20
decay_rate = 0.9
optimizer = torch.optim.Adam(model.parameters(),lr=lr)
loss_fn = nn.MSELoss()

st = time.time()
loss_list = []
# Load model
model = model.cuda()
for epoch in range(num_epoch):
    loss_list = []
    for i_batch, batch in enumerate(train_dataloader):
        x = batch['seq'].cuda() 
        y = batch['logP'].cuda()
        x = x.long()
        y = y.float()
        pred = model(x)
        pred = pred.squeeze(-1)
        #train_loss = loss_fn(pred, y)
        loss = loss_fn(pred,y)
        for g in optimizer.param_groups:
            g['lr'] = lr
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        loss_list.append(loss.data.cpu().numpy())
    lr *= decay_rate
    train_loss = np.mean(np.array(loss_list))
    print (str(epoch+1)+'th train loss:',train_loss,lr)
    
end = time.time()
print ('Time:', end-st)
model.eval()
loss_list = []
with torch.no_grad():
    for i_batch, batch in enumerate(test_dataloader):
        x = batch['seq'].cuda() 
        y = batch['logP'].cuda()
        x = x.long()
        y = y.float()
        pred = model(x)
        pred = pred.squeeze(-1)
        loss = loss_fn(pred, y)
        loss_list.append(loss.data.cpu().numpy())
valid_loss = np.mean(np.array(loss_list))
print ('test loss: ',valid_loss)


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from rdkit import Chem
from rdkit.Chem.Crippen import MolLogP

from torch.utils.data import Dataset, DataLoader

import numpy as np
import time
########## Prepare data ##########

class ConvDataset(Dataset):
    
    def __init__(self,maxlen,c_to_i,smiles_list,property_list):
        self.smiles_list = smiles_list
        self.maxlen = maxlen
        self.c_to_i = c_to_i
        sequence_list = self.encode_smiles()
        self.sequence_list = sequence_list
        #sequence_list = np.array(sequence_list)
        #self.sequence_list = torch.from_numpy(sequence_list) # x
        self.property_list = torch.from_numpy(np.array(property_list)) # y
   
    def encode_smiles(self):
        smiles_list = self.smiles_list
        c_to_i = self.c_to_i
        maxlen = self.maxlen
        sequence_list = []
        for smiles in smiles_list:
            sequence = []
            for s in smiles:
                sequence.append(c_to_i[s])
            sequence = torch.from_numpy(np.array(sequence))
            sequence_list.append(sequence)
        return sequence_list

    def __len__(self):
        return len(self.smiles_list)

    def __getitem__(self, idx):
        sample = dict()
        sample['seq'] = self.sequence_list[idx]
        sample['logP'] = self.property_list[idx]
        return sample


class ConvRegressor(torch.nn.Module):
    
    def __init__(self, n_channel=128, n_conv_layer = 10, kernel_size=3, n_char=46,maxlen = 64):
        super(ConvRegressor, self).__init__()
        convolution_layers = []
        length_sequence = [64]
        stride = 1
        dilation = 1
        padding = kernel_size//2
        for i in range(n_conv_layer):
            l = (length_sequence[-1] + 2 * padding - dilation * (kernel_size - 1) - 1)/stride + 1
            l = int(l)
            length_sequence.append(l)
        for i in range(n_conv_layer):
            convolution_layers.append(nn.Conv1d(n_channel,n_channel,kernel_size,stride,padding = padding))
        self.conv = nn.ModuleList(convolution_layers)
        self.fc = nn.Linear(length_sequence[-1] * n_channel, 1)
        self.embedding = nn.Embedding(n_char, n_channel)
        self.activation = nn.ReLU()

    def forward(self, x):
        retval = x
        retval = self.embedding(retval)
        retval = retval.permute((0,2,1))
        # Pass conv and dropout
        for layer in self.conv:
            #print ('shape',retval.shape)
            retval = layer(retval)
            retval = self.activation(retval)
        ###### Flatten           
        #retval = torch.mean(retval,-1)
        retval = retval.view(retval.size(0), -1)  
        #retval = retval.unsqueeze(-1)
        retval = self.fc(retval)
        return retval

####### Loading data ########
def load_data(directory,maxlen,num):
    f = open(directory,'r')
    smiles_list = []
    cnt = 0
    while cnt < num:
        line = f.readline()
        words = line.strip().split('\t')
        smiles = words[-1]
        if len(smiles) <= maxlen-1:
            cnt += 1
            smiles_list.append(words[-1])
    return smiles_list

# Encoding
def get_c_to_i(smiles_list):
    c_to_i = dict()
    for smiles in smiles_list:
        for letter in smiles:
            if letter not in c_to_i:
                c_to_i[letter] = len(c_to_i)
    return c_to_i

# Padding
def adjust_smiles(smiles_list,maxlen):
    for i in range(len(smiles_list)):
        smiles_list[i] = smiles_list[i].ljust(maxlen,'X')

def calculate_logp(smiles_list):
    logp_list = []
    for smiles in smiles_list:
        mol = Chem.MolFromSmiles(smiles)
        logp = MolLogP(mol)
        logp_list.append(logp)
    return logp_list

# Prepare data
maxlen = 64
num_data = 20000

smiles_list = load_data('smiles.txt',maxlen,num_data)
logp_list = calculate_logp(smiles_list)
adjust_smiles(smiles_list,maxlen)
c_to_i = get_c_to_i(smiles_list)

num_train = 15000

# Make train/test/dataloader
train_smiles = smiles_list[:num_train]
test_smiles = smiles_list[num_train:num_data]
train_logp = logp_list[:num_train]
test_logp = logp_list[num_train:num_data]
train_dataset = ConvDataset(maxlen,c_to_i,train_smiles, train_logp)
test_dataset = ConvDataset(maxlen,c_to_i,test_smiles, test_logp)

#Dataloader
train_dataloader = DataLoader(train_dataset, batch_size=32, num_workers=1)
test_dataloader = DataLoader(test_dataset, batch_size=32, num_workers=1)

### Decay test
num_layer = 3

# Set trainig parameter
model = ConvRegressor(128, num_layer, 5, len(c_to_i),maxlen)
lr = 1e-5
#lr_decay = 0.9
lr_decay = 1
num_epoch = 100
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
#optimizer = torch.optim.SGD(model.parameters(), lr=lr)
loss_fn = nn.MSELoss()


loss_list = []
st = time.time()

# Load model
model = model.cuda()

for epoch in range(num_epoch):
    epoch_loss = []
    for i_batch, batch in enumerate(train_dataloader):
        x = batch['seq'].cuda() 
        y = batch['logP'].cuda()
        x = x.long()
        y = y.float()
        pred = model(x)
        pred = pred.squeeze(-1)
        loss = loss_fn(pred, y)
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        optimizer.lr = lr
        loss_list.append(loss.data.cpu().numpy())
        epoch_loss.append(loss.data.cpu().numpy())
    lr *= lr_decay
    print (epoch, 'loss: ',np.mean(np.array(loss_list)),lr)
end = time.time()
print ('Time:', end-st)

model.eval()
loss_list = []
with torch.no_grad():
    for i_batch, batch in enumerate(test_dataloader):
        x = batch['seq'].cuda() 
        y = batch['logP'].cuda()
        x = x.long()
        y = y.float()
        pred = model(x)
        pred = pred.squeeze(-1)
        loss = loss_fn(pred, y)
        loss_list.append(loss.data.cpu().numpy())
print ('test loss: ',np.mean(np.array(loss_list)))

# Change model capacity
n_channel = 64
num_layer = 3
train_loss_list = []
valid_loss_list = []
n = 10
i = 2
model = ConvRegressor(n_channel, num_layer, i+1, len(c_to_i),maxlen)
lr = 1e-4
num_epoch = 20
weight_decay = 1e-4
optimizer = torch.optim.Adam(model.parameters(),lr=lr)
loss_fn = nn.MSELoss()

st = time.time()
loss_list = []
# Load model
model = model.cuda()
for epoch in range(num_epoch):
    loss_list = []
    for i_batch, batch in enumerate(train_dataloader):
        x = batch['seq'].cuda() 
        y = batch['logP'].cuda()
        x = x.long()
        y = y.float()
        pred = model(x)
        pred = pred.squeeze(-1)
        loss = loss_fn(pred, y)
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        loss_list.append(loss.data.cpu().numpy())
end = time.time()
print ('Time:', end-st)
train_loss = np.mean(np.array(loss_list))
print (str(i+1) + ' th final loss:',train_loss)
train_loss_list.append(train_loss)
model.eval()
loss_list = []

with torch.no_grad():
    for i_batch, batch in enumerate(test_dataloader):
        x = batch['seq'].cuda() 
        y = batch['logP'].cuda()
        x = x.long()
        y = y.float()
        pred = model(x)
        pred = pred.squeeze(-1)
        loss = loss_fn(pred, y)
        loss_list.append(loss.data.cpu().numpy())
valid_loss = np.mean(np.array(loss_list))
print (str(i+1)+' th test loss: ',valid_loss)
valid_loss_list.append(valid_loss)

'''
import matplotlib.pyplot as plt

x = np.arange(1,n+1)
plt.plot(x,train_loss_list,label='train')
plt.plot(x,valid_loss_list,label='valid')
plt.legend()
plt.show()
'''


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from rdkit import Chem
from rdkit.Chem.Crippen import MolLogP

from torch.utils.data import Dataset, DataLoader

import numpy as np
import time
########## Prepare data ##########

class ConvDataset(Dataset):
    
    def __init__(self,maxlen,c_to_i,smiles_list,property_list):
        self.smiles_list = smiles_list
        self.maxlen = maxlen
        self.c_to_i = c_to_i
        sequence_list = self.encode_smiles()
        self.sequence_list = sequence_list
        #sequence_list = np.array(sequence_list)
        #self.sequence_list = torch.from_numpy(sequence_list) # x
        self.property_list = torch.from_numpy(np.array(property_list)) # y
   
    def encode_smiles(self):
        smiles_list = self.smiles_list
        c_to_i = self.c_to_i
        maxlen = self.maxlen
        sequence_list = []
        for smiles in smiles_list:
            sequence = []
            for s in smiles:
                sequence.append(c_to_i[s])
            sequence = torch.from_numpy(np.array(sequence))
            sequence_list.append(sequence)
        return sequence_list

    def __len__(self):
        return len(self.smiles_list)

    def __getitem__(self, idx):
        sample = dict()
        sample['seq'] = self.sequence_list[idx]
        sample['logP'] = self.property_list[idx]
        return sample


class ConvRegressor(torch.nn.Module):
    
    def __init__(self, n_channel=128, n_conv_layer = 10, kernel_size=3, n_char=46,maxlen = 64):
        super(ConvRegressor, self).__init__()
        convolution_layers = []
        length_sequence = [64]
        stride = 1
        dilation = 1
        padding = kernel_size//2
        for i in range(n_conv_layer):
            l = (length_sequence[-1] + 2 * padding - dilation * (kernel_size - 1) - 1)/stride + 1
            l = int(l)
            length_sequence.append(l)
        for i in range(n_conv_layer):
            convolution_layers.append(nn.Conv1d(n_channel,n_channel,kernel_size,stride,padding = padding))
        self.conv = nn.ModuleList(convolution_layers)
        self.fc = nn.Linear(length_sequence[-1] * n_channel, 1)
        self.embedding = nn.Embedding(n_char, n_channel)
        self.activation = nn.ReLU()

    def forward(self, x):
        retval = x
        retval = self.embedding(retval)
        retval = retval.permute((0,2,1))
        # Pass conv and dropout
        for layer in self.conv:
            #print ('shape',retval.shape)
            retval = layer(retval)
            retval = self.activation(retval)
        ###### Flatten           
        #retval = torch.mean(retval,-1)
        retval = retval.view(retval.size(0), -1)  
        #retval = retval.unsqueeze(-1)
        retval = self.fc(retval)
        return retval

####### Loading data ########
def load_data(directory,maxlen,num):
    f = open(directory,'r')
    smiles_list = []
    cnt = 0
    while cnt < num:
        line = f.readline()
        words = line.strip().split('\t')
        smiles = words[-1]
        if len(smiles) <= maxlen-1:
            cnt += 1
            smiles_list.append(words[-1])
    return smiles_list

# Encoding
def get_c_to_i(smiles_list):
    c_to_i = dict()
    for smiles in smiles_list:
        for letter in smiles:
            if letter not in c_to_i:
                c_to_i[letter] = len(c_to_i)
    return c_to_i

# Padding
def adjust_smiles(smiles_list,maxlen):
    for i in range(len(smiles_list)):
        smiles_list[i] = smiles_list[i].ljust(maxlen,'X')

def calculate_logp(smiles_list):
    logp_list = []
    for smiles in smiles_list:
        mol = Chem.MolFromSmiles(smiles)
        logp = MolLogP(mol)
        logp_list.append(logp)
    return logp_list

# Prepare data
maxlen = 64
num_data = 20000

smiles_list = load_data('/content/gdrive/My Drive/smiles.txt',maxlen,num_data)
logp_list = calculate_logp(smiles_list)
adjust_smiles(smiles_list,maxlen)
c_to_i = get_c_to_i(smiles_list)

num_train = 15000

# Make train/test/dataloader
train_smiles = smiles_list[:num_train]
test_smiles = smiles_list[num_train:num_data]
train_logp = logp_list[:num_train]
test_logp = logp_list[num_train:num_data]
train_dataset = ConvDataset(maxlen,c_to_i,train_smiles, train_logp)
test_dataset = ConvDataset(maxlen,c_to_i,test_smiles, test_logp)

#Dataloader
train_dataloader = DataLoader(train_dataset, batch_size=32, num_workers=1)
test_dataloader = DataLoader(test_dataset, batch_size=32, num_workers=1)

# Change model capacity
n_channel = 64
num_layer = 3
# L2 regularization test
model = ConvRegressor(n_channel, num_layer, 5, len(c_to_i),maxlen)
lr = 1e-4
num_epoch = 20
weight_decay = 1e-3
#optimizer = torch.optim.Adam(model.parameters(),lr=lr)
optimizer = torch.optim.Adam(model.parameters(), lr=lr,weight_decay=1e-3)
#optimizer = torch.optim.SGD(model.parameters(), lr=lr)
loss_fn = nn.MSELoss()

st = time.time()
loss_list = []
# Load model
model = model.cuda()
for epoch in range(num_epoch):
    loss_list = []
    for i_batch, batch in enumerate(train_dataloader):
        x = batch['seq'].cuda() 
        y = batch['logP'].cuda()
        x = x.long()
        y = y.float()
        pred = model(x)
        pred = pred.squeeze(-1)
        #train_loss = loss_fn(pred, y)
        loss = loss_fn(pred,y)
        norm = 0
        for param in model.parameters():
            norm += torch.norm(param)
        #loss = loss + norm * weight_decay
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        loss_list.append(loss.data.cpu().numpy())
    train_loss = np.mean(np.array(loss_list))
    print (str(epoch+1)+'th train loss:',train_loss,norm.data.cpu().numpy())
    
end = time.time()
print ('Time:', end-st)
model.eval()
loss_list = []
with torch.no_grad():
    for i_batch, batch in enumerate(test_dataloader):
        x = batch['seq'].cuda() 
        y = batch['logP'].cuda()
        x = x.long()
        y = y.float()
        pred = model(x)
        pred = pred.squeeze(-1)
        loss = loss_fn(pred, y)
        loss_list.append(loss.data.cpu().numpy())
valid_loss = np.mean(np.array(loss_list))
print ('test loss: ',valid_loss)


1th train loss: 1.6207076 65.80866
2th train loss: 0.5094332 63.855022
3th train loss: 0.28447828 61.998642
4th train loss: 0.21171857 60.162018
5th train loss: 0.17491062 58.39688
6th train loss: 0.1526316 56.679558
7th train loss: 0.12574983 55.030365
8th train loss: 0.1277462 53.419624
9th train loss: 0.11352417 51.85846
10th train loss: 0.11099715 50.348763
11th train loss: 0.101055644 48.88884
12th train loss: 0.09233429 47.466667
13th train loss: 0.09773414 46.093285
14th train loss: 0.08991097 44.752613
15th train loss: 0.08017704 43.466133
16th train loss: 0.084646694 42.22504
17th train loss: 0.085932195 41.010475
18th train loss: 0.07822738 39.846184
19th train loss: 0.08137255 38.711174
20th train loss: 0.07845495 37.615482
Time: 96.31843161582947
test loss:  0.055895764


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from rdkit import Chem
from rdkit.Chem.Crippen import MolLogP

from torch.utils.data import Dataset, DataLoader

import numpy as np
import time
########## Prepare data ##########

class ConvDataset(Dataset):
    
    def __init__(self,maxlen,c_to_i,smiles_list,property_list):
        self.smiles_list = smiles_list
        self.maxlen = maxlen
        self.c_to_i = c_to_i
        sequence_list = self.encode_smiles()
        self.sequence_list = sequence_list
        self.property_list = torch.from_numpy(np.array(property_list)) # y
   
    def encode_smiles(self):
        smiles_list = self.smiles_list
        c_to_i = self.c_to_i
        maxlen = self.maxlen
        sequence_list = []
        for smiles in smiles_list:
            sequence = []
            for s in smiles:
                sequence.append(c_to_i[s])
            sequence = torch.from_numpy(np.array(sequence))
            sequence_list.append(sequence)
        return sequence_list

    def __len__(self):
        return len(self.smiles_list)

    def __getitem__(self, idx):
        sample = dict()
        sample['seq'] = self.sequence_list[idx]
        sample['logP'] = self.property_list[idx]
        return sample


class ConvRegressor(torch.nn.Module):
    
    def __init__(self, n_channel=128, n_conv_layer = 10, kernel_size=3, n_char=46,maxlen = 64):
        super(ConvRegressor, self).__init__()
        convolution_layers = []
        length_sequence = [maxlen]
        stride = 1
        dilation = 1
        padding = kernel_size//2
        self.embedding = nn.Embedding(n_char, n_channel)
        self.activation = nn.ReLU()
        for i in range(n_conv_layer):
            l = (length_sequence[-1] + 2 * padding - dilation * (kernel_size - 1) - 1)/stride + 1
            l = int(l)
            length_sequence.append(l)
        for i in range(n_conv_layer):
            #convolution_layers.append(Convolution(n_channel,n_channel,kernel_size,stride,padding,self.activation))
            #convolution_layers.append(SkipConnection(n_channel,kernel_size,stride,padding,self.activation))
            convolution_layers.append(Inception(n_channel,n_channel,5,1,self.activation))
        self.conv = nn.ModuleList(convolution_layers)
        self.fc = nn.Linear(length_sequence[-1] * n_channel, 1)

    def forward(self, x):
        retval = x
        retval = self.embedding(retval)
        retval = retval.permute((0,2,1))
        # Pass conv and dropout
        for layer in self.conv:
            retval = layer(retval)
            retval = self.activation(retval)
        ###### Flatten           
        retval = torch.reshape(retval,(retval.size(0),-1))
        retval = self.fc(retval)
        return retval

class Convolution(nn.Module):
    
    def __init__(self,n_in,n_out,kernel_size,stride,padding,activation):
        
        super().__init__()
        self.conv = nn.Conv1d(n_in,n_out,kernel_size,stride,padding)
        self.activation = activation

    def forward(self,x):
        retval = self.conv(x)
        retval = self.activation(retval)
        return retval

# New layers
class SkipConnection(nn.Module):
    
    def __init__(self,n_channel,kernel_size,stride,padding,activation):
        super().__init__()
        self.conv1 = nn.Conv1d(n_channel,n_channel,kernel_size,stride,padding)
        self.conv2 = nn.Conv1d(n_channel,n_channel,kernel_size,stride,padding)
        self.activation = activation
    
    def forward(self,x):
        retval = self.conv1(x)
        retval = self.activation(retval)
        retval = self.conv2(retval)
        retval = x + retval
        return self.activation(retval)

class Inception(nn.Module):
    
    def __init__(self,n_in,n_out,max_kernel_size,stride,activation):
        super().__init__()
        maximal_kernel = (max_kernel_size - max_kernel_size//2)*2 + 1
        num_conv = int(maximal_kernel/2) + 1
        self.conv_layers = []
        for i in range(num_conv):
            if i == num_conv-1:
                self.conv_layers.append(nn.Conv1d(n_in,int(n_out/num_conv)+n_out%num_conv,2*i+1,1,padding=i))
            else:
                self.conv_layers.append(nn.Conv1d(n_in,int(n_out/num_conv),2*i+1,1,padding=i))
        self.conv_layers = nn.ModuleList(self.conv_layers)
        self.activation = activation

    def forward(self,x):
        output = []
        for layer in self.conv_layers:
            retval = layer(x)
            retval = self.activation(retval)
            output.append(retval)
        output = torch.cat(output,1)

        return output

####### Loading data ########
def load_data(directory,maxlen,num):
    f = open(directory,'r')
    smiles_list = []
    cnt = 0
    while cnt < num:
        line = f.readline()
        words = line.strip().split('\t')
        smiles = words[-1]
        if len(smiles) <= maxlen-1:
            cnt += 1
            smiles_list.append(words[-1])
    return smiles_list

# Encoding
def get_c_to_i(smiles_list):
    c_to_i = dict()
    for smiles in smiles_list:
        for letter in smiles:
            if letter not in c_to_i:
                c_to_i[letter] = len(c_to_i)
    return c_to_i

# Padding
def adjust_smiles(smiles_list,maxlen):
    for i in range(len(smiles_list)):
        smiles_list[i] = smiles_list[i].ljust(maxlen,'X')

def calculate_logp(smiles_list):
    logp_list = []
    for smiles in smiles_list:
        mol = Chem.MolFromSmiles(smiles)
        logp = MolLogP(mol)
        logp_list.append(logp)
    return logp_list

# Prepare data
maxlen = 64
num_data = 20000

smiles_list = load_data('/content/gdrive/My Drive/smiles.txt',maxlen,num_data)
logp_list = calculate_logp(smiles_list)
adjust_smiles(smiles_list,maxlen)
c_to_i = get_c_to_i(smiles_list)

num_train = 15000

# Make train/test/dataloader
train_smiles = smiles_list[:num_train]
test_smiles = smiles_list[num_train:num_data]
train_logp = logp_list[:num_train]
test_logp = logp_list[num_train:num_data]
train_dataset = ConvDataset(maxlen,c_to_i,train_smiles, train_logp)
test_dataset = ConvDataset(maxlen,c_to_i,test_smiles, test_logp)

#Dataloader
train_dataloader = DataLoader(train_dataset, batch_size=32, num_workers=1)
test_dataloader = DataLoader(test_dataset, batch_size=32, num_workers=1)

num_layer = 3

# Set trainig parameter
model = ConvRegressor(128, num_layer, 5, len(c_to_i),maxlen)
#print ('state dict: ',model.state_dict)
lr = 1e-4
num_epoch = 5
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
loss_fn = nn.MSELoss()


loss_list = []
st = time.time()

# Load model
model = model.cuda()

save_file = '/content/gdrive/My Drive/model.pt'

for epoch in range(num_epoch):
    epoch_loss = []
    for i_batch, batch in enumerate(train_dataloader):
        x = batch['seq'].cuda() 
        y = batch['logP'].cuda()
        x = x.long()
        y = y.float()
        pred = model(x)
        pred = pred.squeeze(-1)
        loss = loss_fn(pred, y)
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        loss_list.append(loss.data.cpu().numpy())
        epoch_loss.append(loss.data.cpu().numpy())
    print (epoch, 'loss: ',np.mean(np.array(loss_list)))
    if epoch == num_epoch - 1:
        torch.save(model.state_dict(),save_file)

end = time.time()
print ('Time:', end-st)

model.eval()
loss_list = []
with torch.no_grad():
    for i_batch, batch in enumerate(test_dataloader):
        x = batch['seq'].cuda() 
        y = batch['logP'].cuda()
        x = x.long()
        y = y.float()
        pred = model(x)
        pred = pred.squeeze(-1)
        loss = loss_fn(pred, y)
        loss_list.append(loss.data.cpu().numpy())
print ('test loss: ',np.mean(np.array(loss_list)))

model = ConvRegressor(128,num_layer, 5, len(c_to_i),maxlen)
model.load_state_dict(torch.load('/content/gdrive/My Drive/model.pt'))
model.cuda()
model.eval()
loss_list=[]
with torch.no_grad():
  for i_batch,batch in enumerate(test_dataloader):
    x = batch['seq'].cuda()
    y = batch['logP'].cuda()
    x = x.long()
    y = y.float()
    pred = model(x)
    pred = pred.squeeze(-1)
    loss = loss_fn(pred,y)
    loss_list.append(loss.data.cpu().numpy())
print('loss: ',np.mean(np.array(loss_list)))




0 loss:  1.2605041
1 loss:  0.7963927
2 loss:  0.59808636
3 loss:  0.4833417
4 loss:  0.41308168
Time: 28.538957595825195
test loss:  0.110049695
loss:  0.110049695


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from rdkit import Chem
from rdkit.Chem.Crippen import MolLogP

from torch.utils.data import Dataset, DataLoader

import numpy as np
import time
########## Prepare data ##########

class ConvDataset(Dataset):
    
    def __init__(self,maxlen,c_to_i,smiles_list,property_list):
        self.smiles_list = smiles_list
        self.maxlen = maxlen
        self.c_to_i = c_to_i
        sequence_list = self.encode_smiles()
        self.sequence_list = sequence_list
        self.property_list = torch.from_numpy(np.array(property_list)) # y
   
    def encode_smiles(self):
        smiles_list = self.smiles_list
        c_to_i = self.c_to_i
        maxlen = self.maxlen
        sequence_list = []
        for smiles in smiles_list:
            sequence = []
            for s in smiles:
                sequence.append(c_to_i[s])
            sequence = torch.from_numpy(np.array(sequence))
            sequence_list.append(sequence)
        return sequence_list

    def __len__(self):
        return len(self.smiles_list)

    def __getitem__(self, idx):
        sample = dict()
        sample['seq'] = self.sequence_list[idx]
        sample['logP'] = self.property_list[idx]
        return sample


class ConvRegressor(torch.nn.Module):
    
    def __init__(self, n_channel=128, n_conv_layer = 10, kernel_size=3, n_char=46,maxlen = 64):
        super(ConvRegressor, self).__init__()
        convolution_layers = []
        length_sequence = [maxlen]
        stride = 1
        dilation = 1
        padding = kernel_size//2
        self.embedding = nn.Embedding(n_char, n_channel)
        self.activation = nn.ReLU()
        for i in range(n_conv_layer):
            l = (length_sequence[-1] + 2 * padding - dilation * (kernel_size - 1) - 1)/stride + 1
            l = int(l)
            length_sequence.append(l)
        for i in range(n_conv_layer):
            #convolution_layers.append(Convolution(n_channel,n_channel,kernel_size,stride,padding,self.activation))
            #convolution_layers.append(SkipConnection(n_channel,kernel_size,stride,padding,self.activation))
            convolution_layers.append(Inception(n_channel,n_channel,5,1,self.activation))
        self.conv = nn.ModuleList(convolution_layers)
        self.fc = nn.Linear(length_sequence[-1] * n_channel, 1)

    def forward(self, x):
        retval = x
        retval = self.embedding(retval)
        retval = retval.permute((0,2,1))
        # Pass conv and dropout
        for layer in self.conv:
            retval = layer(retval)
            retval = self.activation(retval)
        ###### Flatten           
        retval = torch.reshape(retval,(retval.size(0),-1))
        retval = self.fc(retval)
        return retval

class Convolution(nn.Module):
    
    def __init__(self,n_in,n_out,kernel_size,stride,padding,activation):
        
        super().__init__()
        self.conv = nn.Conv1d(n_in,n_out,kernel_size,stride,padding)
        self.activation = activation

    def forward(self,x):
        retval = self.conv(x)
        retval = self.activation(retval)
        return retval

# New layers
class SkipConnection(nn.Module):
    
    def __init__(self,n_channel,kernel_size,stride,padding,activation):
        super().__init__()
        self.conv1 = nn.Conv1d(n_channel,n_channel,kernel_size,stride,padding)
        self.conv2 = nn.Conv1d(n_channel,n_channel,kernel_size,stride,padding)
        self.activation = activation
    
    def forward(self,x):
        retval = self.conv1(x)
        retval = self.activation(retval)
        retval = self.conv2(retval)
        retval = x + retval
        return self.activation(retval)

class Inception(nn.Module):
    
    def __init__(self,n_in,n_out,max_kernel_size,stride,activation):
        super().__init__()
        maximal_kernel = (max_kernel_size - max_kernel_size//2)*2 + 1
        num_conv = int(maximal_kernel/2) + 1
        self.conv_layers = []
        for i in range(num_conv):
            if i == num_conv-1:
                self.conv_layers.append(nn.Conv1d(n_in,int(n_out/num_conv)+n_out%num_conv,2*i+1,1,padding=i))
            else:
                self.conv_layers.append(nn.Conv1d(n_in,int(n_out/num_conv),2*i+1,1,padding=i))
        self.conv_layers = nn.ModuleList(self.conv_layers)
        self.activation = activation

    def forward(self,x):
        output = []
        for layer in self.conv_layers:
            retval = layer(x)
            retval = self.activation(retval)
            output.append(retval)
        output = torch.cat(output,1)

        return output

####### Loading data ########
def load_data(directory,maxlen,num):
    f = open(directory,'r')
    smiles_list = []
    cnt = 0
    while cnt < num:
        line = f.readline()
        words = line.strip().split('\t')
        smiles = words[-1]
        if len(smiles) <= maxlen-1:
            cnt += 1
            smiles_list.append(words[-1])
    return smiles_list

# Encoding
def get_c_to_i(smiles_list):
    c_to_i = dict()
    for smiles in smiles_list:
        for letter in smiles:
            if letter not in c_to_i:
                c_to_i[letter] = len(c_to_i)
    return c_to_i

# Padding
def adjust_smiles(smiles_list,maxlen):
    for i in range(len(smiles_list)):
        smiles_list[i] = smiles_list[i].ljust(maxlen,'X')

def calculate_logp(smiles_list):
    logp_list = []
    for smiles in smiles_list:
        mol = Chem.MolFromSmiles(smiles)
        logp = MolLogP(mol)
        logp_list.append(logp)
    return logp_list

# Prepare data
maxlen = 64
num_data = 20000

smiles_list = load_data('/content/gdrive/My Drive/smiles.txt',maxlen,num_data)
logp_list = calculate_logp(smiles_list)
adjust_smiles(smiles_list,maxlen)
c_to_i = get_c_to_i(smiles_list)

num_train = 15000

# Make train/test/dataloader
train_smiles = smiles_list[:num_train]
test_smiles = smiles_list[num_train:num_data]
train_logp = logp_list[:num_train]
test_logp = logp_list[num_train:num_data]
train_dataset = ConvDataset(maxlen,c_to_i,train_smiles, train_logp)
test_dataset = ConvDataset(maxlen,c_to_i,test_smiles, test_logp)

#Dataloader
train_dataloader = DataLoader(train_dataset, batch_size=32, num_workers=1)
test_dataloader = DataLoader(test_dataset, batch_size=32, num_workers=1)

num_layer = 3

# Set trainig parameter
model = ConvRegressor(128, num_layer, 5, len(c_to_i),maxlen)
#print ('state dict: ',model.state_dict)
lr = 1e-4
num_epoch = 30
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
loss_fn = nn.MSELoss()


loss_list = []
st = time.time()

# Load model
model = model.cuda()

save_file = 'model.pt'

for epoch in range(num_epoch):
    epoch_loss = []
    for i_batch, batch in enumerate(train_dataloader):
        x = batch['seq'].cuda() 
        y = batch['logP'].cuda()
        x = x.long()
        y = y.float()
        pred = model(x)
        pred = pred.squeeze(-1)
        loss = loss_fn(pred, y)
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        loss_list.append(loss.data.cpu().numpy())
        epoch_loss.append(loss.data.cpu().numpy())
    print (epoch, 'loss: ',np.mean(np.array(loss_list)))
    #if epoch == num_epoch - 1:
        #torch.save(model.state_dict(),save_file)

end = time.time()
print ('Time:', end-st)

model.eval()
loss_list = []
with torch.no_grad():
    for i_batch, batch in enumerate(test_dataloader):
        x = batch['seq'].cuda() 
        y = batch['logP'].cuda()
        x = x.long()
        y = y.float()
        pred = model(x)
        pred = pred.squeeze(-1)
        loss = loss_fn(pred, y)
        loss_list.append(loss.data.cpu().numpy())
print ('test loss: ',np.mean(np.array(loss_list)))




0 loss:  1.1920135
1 loss:  0.73443806
2 loss:  0.5554589
3 loss:  0.45047644
4 loss:  0.38269895
5 loss:  0.3344719
6 loss:  0.2980518
7 loss:  0.2697782
8 loss:  0.24709506
9 loss:  0.22832161
10 loss:  0.21292447
11 loss:  0.20001307
12 loss:  0.18880299
13 loss:  0.178363
14 loss:  0.16924207
15 loss:  0.16135639
16 loss:  0.15448412
17 loss:  0.14793421
18 loss:  0.14193597
19 loss:  0.13668483
20 loss:  0.13153234
21 loss:  0.12686875
22 loss:  0.12243851
23 loss:  0.118330486
24 loss:  0.11482991
25 loss:  0.11148731
26 loss:  0.10807373
27 loss:  0.105053
28 loss:  0.10215597
29 loss:  0.099424034
Time: 184.0579798221588
test loss:  0.0639501


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from rdkit import Chem
from rdkit.Chem.Crippen import MolLogP

from torch.utils.data import Dataset, DataLoader

import numpy as np
import time

class MolDataset(Dataset):

    def __init__(self,maxlen,c_to_i,smiles_list):
        self.smiles_list = smiles_list
        self.maxlen = maxlen
        self.c_to_i = c_to_i
        sequence_list = self.encode_smiles()
        self.length_list = []
        for sequence in sequence_list:
            self.length_list.append(len(sequence))
        self.sequence_list = sequence_list
        self.length_list = np.array(self.length_list)
        self.length_list = torch.from_numpy(self.length_list)

    def encode_smiles(self):
        smiles_list = self.smiles_list
        c_to_i = self.c_to_i
        maxlen = self.maxlen
        sequence_list = []
        for smiles in smiles_list:
            sequence = []
            for s in smiles:
                sequence.append(c_to_i[s])
            sequence_list.append(torch.from_numpy(np.array(sequence)))
        return sequence_list

    def __len__(self):
        return len(self.smiles_list)

    def __getitem__(self, idx):
        sample = dict()
        sample['length'] = self.length_list[idx]
        sample['seq'] = self.sequence_list[idx]
        return sample

def load_data(directory,maxlen,num):
    f = open(directory,'r')
    smiles_list = []
    cnt = 0
    while cnt < num:
        line = f.readline()
        words = line.strip().split('\t')
        smiles = words[-1]
        if len(smiles) <= maxlen-1:
            cnt += 1
            smiles_list.append(words[-1])
    return smiles_list

def get_c_to_i(smiles_list):
    c_to_i = dict()
    for smiles in smiles_list:
        for letter in smiles:
            if letter not in c_to_i:
                c_to_i[letter] = len(c_to_i)
    return c_to_i

def adjust_smiles(smiles_list,maxlen):
    for i in range(len(smiles_list)):
        smiles_list[i] = smiles_list[i].ljust(maxlen,'X')

def add_X(smiles_list):
    n = len(smiles_list)
    for i in range(n):
        smiles_list[i] += 'X'


#Collate fn
def my_collate(batch):
    sample = dict()
    X =  torch.nn.utils.rnn.pad_sequence([b['seq'] for b in batch], 
                                          batch_first=True, padding_value = 42)
    L = torch.Tensor([b['length'] for b in batch])

    sample['seq'] = X
    sample['length'] = L

    return sample


def print_results(results, msg_length):
    line = []
    for r, ml in zip(results, msg_length):
        r = str(round(r, 5))
        line.append(r.ljust(ml))
    print("\t".join(line))


class RNNRegressor(torch.nn.Module):

    def __init__(self, n_feature=128, n_rnn_layer = 1, n_char=46):
        super().__init__()
        self.n_feature = n_feature
        self.encoder = nn.GRU(input_size=n_feature, hidden_size=n_feature, num_layers=n_rnn_layer)
        self.decoder = nn.GRU(input_size=n_feature*2, hidden_size=n_feature, num_layers=n_rnn_layer)
        
        self.mu = nn.Linear(n_feature, n_feature)
        self.logvar = nn.Linear(n_feature, n_feature)

        self.fc = nn.Linear(n_feature, n_char)
        self.embedding = nn.Embedding(n_char, n_feature)


    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5*logvar)
        eps = torch.randn_like(std) #randn_like: Gaussian distribution sampling
        return mu + eps*std

    def forward(self, x, l):
        x_emb = self.embedding(x) # x_emb: B x L x F
        x_emb = x_emb.permute((1,0,2)) # x_emb: L x B x F
        enc_output, _= self.encoder(x_emb)
        z = []
        for i in range(len(l)):
            z.append(enc_output[l[i]-1,i])
        z = torch.stack(z, 0)

        mu = self.mu(z)
        logvar = self.logvar(z)
        sampled_z = self.reparameterize(mu, logvar) # z: B x F
        dec_input = torch.cat([torch.ones(1, x_emb.size(1), x_emb.size(2)).cuda(), x_emb], 0) # dec_input: (L+1) x B x F: Start codon + initial string
        repeat_z = sampled_z.unsqueeze(0).repeat(dec_input.size(0), 1, 1) # z: (L+1) x B x F
        dec_input = torch.cat([dec_input, repeat_z], -1)
        dec_output, _ = self.decoder(dec_input)
        dec_output = dec_output[:-1]
        dec_output = self.fc(dec_output)

        loss1 = 0
        loss_fn = torch.nn.CrossEntropyLoss(reduction='mean')
        for i in range(len(l)):
            loss1 += loss_fn(dec_output[:(l[i]+1),i,:], x[i,:(l[i]+1)])
        loss2 = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())

        loss1/=len(dec_output)      
        loss2/=len(dec_output)

        return loss1, loss2

    def indices_to_string(self, indices, i_to_c):
        return ''.join([i_to_c[i] for i in indices])

    def sample(self):
        sampled_z = torch.randn(1, self.n_feature).cuda()
        token = torch.ones((1, self.n_feature)).cuda()
        initial_state = torch.zeros((1, 1, self.n_feature)).cuda()

        gen_smiles = []
        maxlen = 64
        for i in range(maxlen):
            dec_input = torch.cat([token, sampled_z], -1).unsqueeze(0)
            output, initial_state = self.decoder(dec_input, initial_state)
            output = F.softmax(self.fc(output), -1).squeeze()
            #if i<1: print (output)
            m = torch.distributions.categorical.Categorical(output)
            sampled_idx = m.sample()
            gen_smiles.append(int(sampled_idx))
            token = self.embedding(torch.tensor([sampled_idx]).cuda())
        return gen_smiles

# Make data
maxlen = 64
smiles_list = load_data('/content/gdrive/My Drive/smiles.txt',maxlen,20000)
c_to_i = get_c_to_i(smiles_list)
add_X(smiles_list)
c_to_i['X'] = len(c_to_i)
i_to_c = dict()
for char in c_to_i:
    index = c_to_i[char]
    i_to_c[index] = char

#Dataset
train_smiles = smiles_list[:10000]
test_smiles = smiles_list[10000:]
train_dataset = MolDataset(maxlen,c_to_i,train_smiles)
test_dataset = MolDataset(maxlen,c_to_i,test_smiles)

train_dataloader = DataLoader(train_dataset, batch_size=128, num_workers=1, collate_fn=my_collate, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=128, num_workers=1, collate_fn=my_collate)

print ('len',len(c_to_i))

#Train model
import time
lr = 1e-4
num_epoch = 51
model = RNNRegressor(512, 1, len(c_to_i)).cuda()
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
loss_fn = nn.MSELoss()
ratio = 10


loss_list = []
st = time.time()

title_list = ['epoch', 'construction loss','kl loss']
length_list = [len(title) for title in title_list]

first_msg = title_list[0] + '\t' + title_list[1] + '\t' + title_list[2]
epoch_list = [5,10,50]


print (first_msg)
for epoch in range(num_epoch):
    epoch_loss = []
    for i_batch, batch in enumerate(train_dataloader):
        model.zero_grad()
        x = batch['seq'].cuda().long()
        l = batch['length'].cuda().long()
        loss1, loss2 = model(x, l)
        loss = loss1 + loss2*ratio
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

        optimizer.step()
        epoch_loss.append([loss1.data.cpu().numpy(), loss2.data.cpu().numpy()])
    ####### See reconstruction
    if epoch in epoch_list:
        #fn = f'/content/gdrive/My Drive/Colab Notebooks/save/save_{epoch}.pt'
        fn = f'{epoch}.pt'
        torch.save(model.state_dict(), fn)
    if True: 
        results = [epoch, np.mean(np.array(epoch_loss)[:,0]),np.mean(np.array(epoch_loss)[:,1])]
        print_results(results,length_list)
end = time.time()
print ('Time:', end-st)


'''
######### generate molecules
from rdkit import Chem

model = RNNRegressor(512, 1, len(c_to_i)).cuda()

for epoch in epoch_list:
    #fn = f'/content/gdrive/My Drive/Colab Notebooks/save/save_{i}.pt'
    fn = f'{epoch}.pt'
    model.load_state_dict(torch.load(fn))

    generated = []
    for i in range(100):
        sequence = model.sample()
        smiles = model.indices_to_string(sequence,i_to_c) # Contains X
        smiles = smiles.split('X')[0] # Only gather smiles right before X
        generated.append(smiles)    
    cnt = 0
    well_generated_molecule = []
    for g in generated:
        if Chem.MolFromSmiles(g) is not None: 
            well_generated_molecule.append(g)
            cnt += 1
    for g in well_generated_molecule:
        print (g)
    print (cnt, 'molecules are well generated!')
'''


len 43
epoch	construction loss	kl loss
0    	4.53722          	1.53089
1    	2.88129          	0.01472
2    	2.4653           	0.00707
3    	2.25746          	0.00519
4    	2.11105          	0.00391
5    	1.98834          	0.00331
6    	1.88707          	0.00248
7    	1.80558          	0.00204
8    	1.74181          	0.00187
9    	1.68906          	0.00172
10   	1.6455           	0.00177
11   	1.60703          	0.0015 
12   	1.57069          	0.00138
13   	1.54277          	0.00131
14   	1.51091          	0.0014 
15   	1.48797          	0.00138
16   	1.46461          	0.00143
17   	1.44197          	0.0015 
18   	1.42058          	0.0011 
19   	1.40108          	0.00105
20   	1.38528          	0.00107
21   	1.36543          	0.00099
22   	1.35124          	0.00103
23   	1.3355           	0.00116
24   	1.32124          	0.00207
25   	1.30906          	0.00217
26   	1.29781          	0.00233
27   	1.28651          	0.00206
28   	1.27897          	0.00121
29   	1.2696           	0.00164
3

"\n######### generate molecules\nfrom rdkit import Chem\n\nmodel = RNNRegressor(512, 1, len(c_to_i)).cuda()\n\nfor epoch in epoch_list:\n    #fn = f'/content/gdrive/My Drive/Colab Notebooks/save/save_{i}.pt'\n    fn = f'{epoch}.pt'\n    model.load_state_dict(torch.load(fn))\n\n    generated = []\n    for i in range(100):\n        sequence = model.sample()\n        smiles = model.indices_to_string(sequence,i_to_c) # Contains X\n        smiles = smiles.split('X')[0] # Only gather smiles right before X\n        generated.append(smiles)    \n    cnt = 0\n    well_generated_molecule = []\n    for g in generated:\n        if Chem.MolFromSmiles(g) is not None: \n            well_generated_molecule.append(g)\n            cnt += 1\n    for g in well_generated_molecule:\n        print (g)\n    print (cnt, 'molecules are well generated!')\n"

In [ ]:
from rdkit import Chem

model = RNNRegressor(512, 1, len(c_to_i)).cuda()

for epoch in epoch_list:
    #fn = f'/content/gdrive/My Drive/Colab Notebooks/save/save_{i}.pt'
    fn = f'{epoch}.pt'
    model.load_state_dict(torch.load(fn))

    generated = []
    for i in range(100):
        sequence = model.sample()
        smiles = model.indices_to_string(sequence,i_to_c) # Contains X
        smiles = smiles.split('X')[0] # Only gather smiles right before X
        generated.append(smiles)    
    cnt = 0
    well_generated_molecule = []
    for g in generated:
        if Chem.MolFromSmiles(g) is not None: 
            well_generated_molecule.append(g)
            cnt += 1
    for g in well_generated_molecule:
        print (g)
    print (cnt, 'molecules are well generated!')

c1ncc1
CCCOC(=O)[O-]
COc1ccc(Cl)cc1
CN1c2cccc2c1C(=O)OCC(C)=O
NC(=O)/CC1=CNCC(C#N)C(O)Oc2cccc2c1CC=O
CCOC(=O)C(F)(O)C(=O)C(C)Oc1ccccc1
C/C(=O)[O-]
7 molecules are well generated!
Cc1nc(C)c(C)n1C
COc1cccc(C(F)(F)F)c1OC
Cn1c(=O)n(C)n1C
CC(C)OCC(O)C(N)Oc1cccc(Cl)c1
Cc1nnc2[nH]c(N3CCCCC3)c(Br)cc12
Cc1ccc(CC2C(=O)CC23CCNCC(C)C3)nc1-c1ccccc1
C1CCN(C(=O)CN(C)C)c1O
CCCCCCCC(=O)OCC(C)OC(N)C(=O)N\c1ccccc1
CCCCCN
CCC(C)(O)COc1cccc(Br)c1
Oc1cc([N+](=O)[O-])ccc1
CC1(C)C=C(c2ccccc2)c2cc(C)c(C(C#N)=C(C)C)c([O-])c1-2
O=C(CN1CCc2ccccc21)CC(F)(Br)Cl
Cc1ccc(C2N=C(C)C(=O)C2=O)cc1
CCN(CCC#N)C(C#N)=C(CO)CC(C)=O
O=C1NC(c2ccccc2)c(F)c1C
CCCCC(=O)NC(=O)NN1CCOCCN1
Cc1ccc([N+](=O)[O-])cc1
18 molecules are well generated!
CC1=NC(c2ccc(Cl)cc2)OC(N)=C1C(=O)Nc1ccc(F)cc1F
Cn1c(N/N=C/c2cccc(C(=O)O)c2)nc2ccccc2c1=O
CC1=CC(C)(C)NC1=O
CCOC(=O)C(NC(=O)Nc1ccccc1Cl)(C(Cl)=N/O)C(F)(F)F
CC(=N\OC(=O)c1ccccc1)/C(=N\O)CCO
O=C(O)CC(=O)Nc1ccc(Cl)c(Cl)c1[N+](=O)[O-]
O=[N+]([O-])c1ccc(/C(C#N)=C/c2ccccc2F)cc1OC
CC(=O)CC.[Cl-]
CCOC(=O